### ISSUE TITLE
Validate GraphQL schema before deploying

### ISSUE THREAD

**Issue by lightsofapollo** [sid88in/serverless-appsync-plugin#104]
I ran into an issue where I was using input types in my output types (obviously wrong) but I did not figure this out until I had pasted my schema into the appsync schema section in the console.

It appears as though if the schema is invalid the cloudformation update will simply proceed without updating the schema. There is an argument this is a bug in AWS but it would be nice if this lib would validate the graphql schema prior to upload to prevent this issue.

Can take a stab at this if agreed it's worthwhile.

**Comment by sid88in** [comment]
sounds good @lightsofapollo

**Comment by lightsofapollo** [comment]
@sid88in Excellent I will take a pass at it soon.

**Comment by rodrigorellana** [comment]
year 2023 same issue =)
