### ISSUE TITLE
<Really Cool> AppSync Simulator for Local Development

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#112]
Refer : https://github.com/ConduitVC/appsync-serverless-emulator-example 

This simulator is using this plugin :)

**Comment by sid88in** [comment]
@lightsofapollo really cool. Good job!

**Comment by lightsofapollo** [comment]
Thanks @sid88in we're still actively iterating on it for our own usage but we're ready for others to try it. Some new changes will be landing soon so the dynamodb emulator is bundled and all the dependencies are then contained within the nodejs ecosystem (+ java).

**Comment by sid88in** [comment]
sounds good! maybe lets explore if we can integrate this in the plugin and make it more powerful. I am in full support :)
