### ISSUE TITLE
update app sync post version 1.0

### ISSUE THREAD

**Issue by apski** [sid88in/serverless-appsync-plugin#113]
after version 1.0 is there a way to simply update the app sync endpoints. 

running sls deploy creates a new endpoint with new API keys.

**Comment by KeKs0r** [comment]
I am wondering the same thing. It does not create a new API  for me, but it also does not update the existing appsync. Maybe my configuration is also wrong.

**Comment by Kalm004** [comment]
@sid88in this issue was closed, what was the response to the question? after changing the GraphQL schema I'm not able to do a new "sls deploy", not to the same neither to a new one AppSync.
