### ISSUE TITLE
Schema validation fails on interfaces

### ISSUE THREAD

**Issue by heylookalive** [sid88in/serverless-appsync-plugin#116]
Appsync currently supports types implementing multiple interfaces but with older syntax:
`type X implements Int1, Int2`
rather than the newer style which the Apollo validator expects:
`type X implements Int1 & Int2`

Is there any way to tell the validator to allow both?

**Comment by trilliput** [comment]
Yes it's possible using a parse option. I pushed a fairly simple fix, but can't test it right now. @heylookalive could you please test my branch and confirm AppSync accepts it?

**Comment by bboure** [comment]
This seems to be working now.
