### ISSUE TITLE
Fix broken schema.graphql path from previous merged PR

### ISSUE THREAD

**Issue by Znergy** [sid88in/serverless-appsync-plugin#131]
Breaking changes in the last merge #127. I've added a PR (#130) to fix the pathing issue which was causing deployments to try and pull from the example project `schema.graphql`.

You can test the pathing issue by updating to the most recent version of `serverless-appsync-plugin` and trying to `sls deploy`.

**Comment by fgiarritiello** [comment]
Thanks @Znergy. Can anyone please release this new version?

**Comment by Znergy** [comment]
It looks like it was merged in 2 hours ago (#130).

**Comment by deadcoder0904** [comment]
You can close this one

**Comment by fgiarritiello** [comment]
What version should I download to see this change?

**Comment by rohanray** [comment]
is it released to npm registry?

**Comment by deadcoder0904** [comment]
Use v1.0.1 till then as it is not released yet. Only merged 4 hours ago. The earlier one v1.0.2 was merged 9 hours ago but it contains this error.

If you still want to use the version with the fix to this issue, then try https://stackoverflow.com/a/36743127/6141587 with https://github.com/sid88in/serverless-appsync-plugin/pull/130

**Comment by sid88in** [comment]
thanks @Znergy I just published 1.0.3 https://www.npmjs.com/package/serverless-appsync-plugin
