### ISSUE TITLE
Aurora or SQL Database as DataSource

### ISSUE THREAD

**Issue by marcelalburg** [sid88in/serverless-appsync-plugin#148]
Hello,

are there any plans to support the SQL Datasources ?

Info: https://aws.amazon.com/de/blogs/mobile/aws-appsync-adds-support-for-sql-databases-with-amazon-aurora-connector/

Thanks

**Comment by buggy** [comment]
AppSync doesn't actually support SQL Datasources. The blueprint uses a Lambda to connect to Aurora and request data so you only need a Lambda data source.

**Comment by marcelalburg** [comment]
True. Sorry i read this site wrong than.

**Comment by can-kayacan** [comment]
That's not true anymore, to my knowledge. Now you can target Aurora with AppSync. Here is a mapping template to write to Aurora.

`
{
    "version" : "2017-02-28",
    "operation": "Invoke",
    #set($id = $util.autoId())
    "payload": {
      "sql":"INSERT INTO comments VALUES ('$id', :AUTHOR, :POST_ID, :CONTENT, 1, 0)",
      "variableMapping": {
        ":AUTHOR" : "$context.arguments.author",
        ":POST_ID" : "$context.arguments.postId",
        ":CONTENT" : "$context.arguments.content"
      },
      "responseSQL": "SELECT id, postId, author, content, upvotes, downvotes FROM comments WHERE id = '$id'"
    }
}
`
