### ISSUE TITLE
Serverless graphiql command

### ISSUE THREAD

**Issue by maddijoyce** [sid88in/serverless-appsync-plugin#150]
Hi @sid88in,

I wrote a serverless plugin so that you can run ```sls graphiql -u username -p password``` and launch a graphiql instance connected to your appsync api - https://github.com/maddijoyce/serverless-appsync-graphiql.

I realized as I updated it that it's fairly heavily tied to your existing plugin. Would you be interested in having my plugin merged into yours? I wanted to check before I fork your plugin and try adding the command.

Cheers,
Maddi

**Comment by bboure** [comment]
Hi @maddijoyce That sounds good! Thanks for the effort. 
Do you think you could add support for API_KEY and OPENID_CONNECT authentications ?

**Comment by maddijoyce** [comment]
I've opened a pull request at #152, let me know your thoughts there. Cheers!

**Comment by imolorhe** [comment]
I wonder how you feel about a command for [Altair](https://altair.sirmuel.design/) as well 🙂

**Comment by Sunac** [comment]
Vote for Altair too. My fav, especially now when it supports AppSync subscriptions.
