### ISSUE TITLE
Bring back multiple API support

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#157]
https://github.com/sid88in/serverless-appsync-plugin/issues/154

@ZY-Ang

**Comment by ZY-Ang** [comment]
Working on a version that keeps the `logicalIds` the same

**Comment by sid88in** [comment]
@ZY-Ang any updates?

**Comment by petergaultney** [comment]
I'm really interested in this as well. I'm not sure I'm ready to dive into the code and fix it myself, but would love to know what the chances are that it will be making it back into master at some point.

**Comment by sid88in** [comment]
this was deployed!
