### ISSUE TITLE
WARNING when running with plugin

### ISSUE THREAD

**Issue by adrianhall** [sid88in/serverless-appsync-plugin#159]
When running my deployment with the following:

```
SLS_DEBUG=* sls deploy -v
```

I get the following warning:

```
Serverless: WARNING: Plugin ServerlessAppsyncPlugin uses deprecated hook before:deploy:initialize,
                     use package:initialize hook instead
```

`sls --version` shows 1.32.0

**Comment by bboure** [comment]
Thanks, looks like we need to upgrade. 
Would you like to open a PR for that? 
apparently this was deprecated in v1.12.0 https://github.com/serverless/serverless/commit/0af0ef95b18dafc30736da9eabab915d99d0c1b9

**Comment by adrianhall** [comment]
Yeah - it looks like it isn't a big change (actually, a one-liner), so I'll do it when I get home tonight.
