### ISSUE TITLE
RFC: Combine multiple services in one API

### ISSUE THREAD

**Issue by aeby** [sid88in/serverless-appsync-plugin#162]
Assume I have two different services each creating a set of lambda functions and I want to expose them through one AppSync schema. What would be the best approach to do this?
It would be nice if each service could define its `dataSources` and `mappingTemplates` and then somehow extend the schema definition.

**Comment by bboure** [comment]
Hi @aeby,
Let me see if I got this right. 
You have 2 serverless services, each creating lambda functions and you want to create a third one that uses those lambdas as data source?

You can do that using [Output Exports](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-cloudformation-outputs)


Then in your appsync stack, you can reference them with ` {Ref: OutpuName}`

**Comment by aeby** [comment]
Hi @bboure!

Thanks for the fast reply. Yes that's the idea and how I do it at the moment. But what would be nice from a development perspective if one cloud write the schema definition inside the services and therefore extend the base schema of the appsync stack. Does that make sense? 

According to this [SO answer](https://stackoverflow.com/questions/51398964/aws-cloudformation-appsync-extend-query) type extensions do not work and are not planned.

**Comment by bboure** [comment]
do you want to extend types or just reuse them ?
if you just want to define your types in the services and reuse them, then maybe this could be achieved with some templating system or a simple file mege ?
