### ISSUE TITLE
Update suggestion for the Serverless.yml 

### ISSUE THREAD

**Issue by pjonson2** [sid88in/serverless-appsync-plugin#164]
Hello, I'm trying to use your plugin. It seems like a fantastic addition!! I'm finding it very difficult to get started because I'm not sure what information I need to replace in the Serverless.yml part of the README. Would you be willing to update the Serverless.yml part of the README into smaller "chunks" that explains the additional steps that one would need to take to successfully integrate your plugin?

**Comment by sid88in** [comment]
@pjonson2 maybe you can go through the blog and serverless templates to get started with? Also more than happy to answer any specific questions you may have. In addition, if you find a way to improve the documentation, please feel free to create a PR :)
