### ISSUE TITLE
How to use serverless graphql-playground 

### ISSUE THREAD

**Issue by pjonson2** [sid88in/serverless-appsync-plugin#166]
Hello there, thank you so much for this plugin! I have found it to be very useful!!! I'm stuck because I'm not sure how to work within the graphql playground. Is it just like the AWS AppSync Query console? If so, how do I send json objects to a query? Can you show an example of a query and mutation that uses json objects within the README?

**Comment by sid88in** [comment]
please refer to playground documentation
