### ISSUE TITLE
Only one resolver is allowed per field

### ISSUE THREAD

**Issue by pmd30011991** [sid88in/serverless-appsync-plugin#167]
Error
```GraphQlResolverClassSessionattendances - Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException;```
My Schema
```
type SessionAttendance {
    id: Int
    user: User
    date: String
    status: AttendanceStatus
}
type ClassSession {
    id: Int
    date: String
    remark: String
    attendances:[SessionAttendance]
}
type Class {
    id: Int
    tutor: String
    code:String
    location: Location
    subject: Subject
    level: String
    subLevel: String
    branch: String
    studentCount: Int
    sessionConfigs:[ClassSessionConfig]
    sessions(limit: Int): [ClassSession]
    total: Int
    price: Float
    students: [User!]
```

My Mapping

```

      - dataSource: GetSessionAttendanceLambda
        type: ClassSession
        field: attendances
        request: "get-session-attendance-request.vtl"
        response: "get-session-attendance-response.vtl"
        
      - dataSource: GetClassSessionLambda
        type: ClassPayload
        field: sessions
        request: "get-class-session-request.vtl"
        response: "get-class-session-response.vtl"
```

I already check and confirm there is just only one resolver map to the attendances field

**Comment by kinyat** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=282988

I can reproduce this issue my renaming the resolvers which happens when you upgrade the plugins from an old version.

The currently possible solution is to delete your whole stack and redeploy again.

AWS CloudFormation team has been notified for the issue when I asked their support.

**Comment by danielbayerlein** [comment]
Delete the affected resolver manually and then update the stack.

**Comment by clodal** [comment]
@danielbayerlein How to delete the resolver manually?

**Comment by danielbayerlein** [comment]
@clodal You can remove the resolver manually in the AWS AppSync Console. (Schema -> Select Resolver -> Delete Resolver)

**Comment by clodal** [comment]
Yes i'm at schema. But cannot find Select Resolver or Delete Resolver action. I am creating these resolvers through Amplify though. Maybe that's why.

![Screenshot 2020-03-09 at 4 57 48 PM](https://user-images.githubusercontent.com/8684825/76197477-2c9db100-6227-11ea-8219-e47be34ce238.png)

**Comment by danielbayerlein** [comment]
@clodal The resolvers list is scrollable. If a resolver is connected, you can click on it. Then you come to the resolver detail page. There you will find the delete button.
