### ISSUE TITLE
Updating to 1.0.7 changes API URL

### ISSUE THREAD

**Issue by lindlof** [sid88in/serverless-appsync-plugin#177]
When I change between serverless-appsync-plugin versions 1.0.5 to 1.0.7 AppSync is re-installed and that causes API URL to change.

This is pretty critical because our products are directly using the AppSync API URL. (Why don't we have custom API URLs? We have been trying to get custom AppSync URLs working when using IAM authentication forever and AWS hasn't been able to provide us with a solution.)

**Comment by sid88in** [comment]
+ @ZY-Ang

**Comment by bboure** [comment]
This is related to https://github.com/sid88in/serverless-appsync-plugin/pull/176 I believe.

**Comment by sid88in** [comment]
@bboure @ZY-Ang @lindlof I just published v 1.0.8

**Comment by lindlof** [comment]
@sid88in Thank you!
I tried changing between versions 1.0.5 and 1.0.8. My API URL stayed the same. The problem seems to be fixed.

@vladgolubev I assume that you updated from 1.0.7 to 1.0.8. As far as I understand the problem, fixing it would indeed make the URL change again on that update. You'll avoid this problem only if you skip deploying with 1.0.7. That's great for anyone who didn't deploy 1.0.7 in production (which should be the vast majority as 1.0.7 is very new and you should test the deployment before pushing it to production).
