### ISSUE TITLE
Support pipeline resolvers / functions

### ISSUE THREAD

**Issue by adrianhall** [sid88in/serverless-appsync-plugin#183]
AppSync team recently release pipeline resolvers (aka chain resolvers).

Example CloudFormation:

```
    AppSyncMarkFavoriteStoreFavoriteFunction:
      Type: AWS::AppSync::FunctionConfiguration
      Properties:
        ApiId: { Fn::GetAtt: [ GraphQLApi, ApiId ]}
        Name: storeFavorite
        DataSourceName: DynamoDB
        RequestMappingTemplate: ${file(./mapping-templates/Function-storeFavorite-request.vtl)}
        ResponseMappingTemplate: ${file(./mapping-templates/Function-storeFavorite-response.vtl)}

    AppSyncMarkFavoriteGetLocationFunction:
      Type: AWS::AppSync::FunctionConfiguration
      Properties:
        ApiId: { Fn::GetAtt: [ GraphQLApi, ApiId ]}
        Name: getLocation
        DataSourceName: DynamoDB
        RequestMappingTemplate: ${file(./mapping-templates/Function-getLocation-request.vtl)}
        ResponseMappingTemplate: ${file(./mapping-templates/Function-getLocation-response.vtl)}

    AppSyncMarkFavoriteResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: { Fn::GetAtt: [ GraphQLApi, ApiId ]}
        TypeName: Mutation
        FieldName: markFavorite
        RequestMappingTemplate: ${file(./mapping-templates/Mutation-markFavorite-request.vtl)}
        ResponseMappingTemplate: ${file(./mapping-templates/common-response.vtl)}
        PipelineConfig:
          Functions:
            - { Fn::GetAtt: [ AppSyncMarkFavoriteGetLocationFunction, FunctionName ]}
            - { Fn::GetAtt: [ AppSyncMarkFavoriteStoreFavoriteFunction, FunctionName ]}
```

(Obviously replacing the ${file(...)} with the contents of the file). 

Notable - there is no "DataSourceName" in the Resolver for a pipeline resolver.  Instead, there is a PipelineConfig.

**Comment by rplute** [comment]
Hi, @adrianhall, looks like they already added support? It appears merged into master.

https://github.com/sid88in/serverless-appsync-plugin/pull/181

**Comment by sid88in** [comment]
yeah sorry guys, I have not released a new version :) Pipeline resolvers have been implemented in this plugin. I am waiting for https://github.com/sid88in/serverless-appsync-plugin/pull/182 to be finalized and then will create a new version! cheers

**Comment by adrianhall** [comment]
I'm writing a blog on pipeline resolvers in serverless right now, and this will be featured.

Thanks!  You guys are truly awesome!

**Comment by sid88in** [comment]
wow that's amazing! thanks a lot @adrianhall <3 :)

**Comment by lucallero** [comment]
> I'm writing a blog on pipeline resolvers in serverless right now, and this will be featured.
> 
> Thanks! You guys are truly awesome!

Have you published it?  Please share it if possible. Thanks.

**Comment by adrianhall** [comment]
> > I'm writing a blog on pipeline resolvers in serverless right now, and this will be featured.
> > Thanks! You guys are truly awesome!
> 
> Have you published it? Please share it if possible. Thanks.

Yes - it's been added to my APpSync collection on https://adrianhall.github.io/ - it's also been published in Medium, OpenGRaphQL, and other publications.

**Comment by neerajg5** [comment]
> > > I'm writing a blog on pipeline resolvers in serverless right now, and this will be featured.
> > > Thanks! You guys are truly awesome!
> > 
> > 
> > Have you published it? Please share it if possible. Thanks.
> 
> Yes - it's been added to my APpSync collection on https://adrianhall.github.io/ - it's also been published in Medium, OpenGRaphQL, and other publications.

Hi, I've been trying to find the link of the documentation post. However, could not find. Can someone please share the link.
