### ISSUE TITLE
Add support for Complex Objects / S3 Data Sources

### ISSUE THREAD

**Issue by jzeron** [sid88in/serverless-appsync-plugin#187]
The plugin should support for Complex Objects as Data Sources as described [here](https://aws-amplify.github.io/docs/js/api#complex-objects).

**Comment by marcfielding1** [comment]
Erm you sure it doesn't? I've literally just come across this repo so I was about to test it.

**Comment by marcfielding1** [comment]
You can't just add that type to your schema?

**Comment by jzeron** [comment]
@marcfielding1 I believe you are correct if you configure AMAZON_DYNAMODB as the Data Source type.   It just seemed to me that "S3Object" would have its own Data Source type and configuration for this plugin.  Maybe that's not the case?

It would be great if we had working example and best practices for how to deal with complex object queries, mutations, subscriptions using this plugin.

**Comment by jzeron** [comment]
I'm going to close this because there are many different ways to implement support for S3 upload, mutations, and subscriptions and best practices are going to depend on specific use case and requirements...   the plugin has support for dynamodb which you will need to configure to match meta model for S3 endpoints.
