### ISSUE TITLE
Feature support "RELATIONAL_DATABASE" data sources

### ISSUE THREAD

**Issue by q4e2015** [sid88in/serverless-appsync-plugin#192]
In a future, will you support use DataSource type is RELATIONAL_DATABASE  on AppSync AWS?

**Comment by sid88in** [comment]
good idea. We should add RDBMS data source type.

**Comment by bboure** [comment]
+1 on this.
@q4e2015 are you willing to do a PR for this?

**Comment by q4e2015** [comment]
@bboure Sorry. I'm tried but it not well and the way using rds appsync high cost and my team decided to change using rds through aws lambda. Btw I think should closed this issue.
