### ISSUE TITLE
Is there any way to deploy only resolver templates using serverless deploy?

### ISSUE THREAD

**Issue by manicode097** [sid88in/serverless-appsync-plugin#196]
When I have a change only in resolver template (vtl) I would like to quickly deploy only vtl. Something 
`serverless deploy resolvers `

Like
`serverless deploy function --function <lambda-name>`

**Comment by manicode097** [comment]
> Is this for local testing or a production environment?

At this point, mainly for the development where I need to make frequent changes to the resolvers.

**Comment by cbaron** [comment]
In that case I will point you to [this](https://github.com/ConduitVC/aws-utils/tree/master/packages/appsync-emulator-serverless) package that I maintain to develop appsync applications locally.

**Comment by manicode097** [comment]
Thanks. I will give this a try. Closing this issue.
