### ISSUE TITLE
Expose AppSync API URL to serverless

### ISSUE THREAD

**Issue by Gerharddc** [sid88in/serverless-appsync-plugin#200]
I have some Lambda functions in my Serverless stack that need to trigger AppSync mutations (which I think might be a common use case) and as such they need to know the URL of the deployed AppSync API. The most sensible way to do this would be through an environment variable but it doesn't appear as if though this plugin provides a way to reference the deployed URL so that it can be assigned to an env var.

**Comment by bboure** [comment]
Hi @Gerharddc 

There is a way to reference the deployed url. Just ue the returned value of `Ref`
(See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html)
You just have to know the name of the resource. It is not detailed in the doc but a [quick look at the code](https://github.com/sid88in/serverless-appsync-plugin/blob/master/index.js#L207) can help you find it.

Provided that you use only one API it would be: `Ref::GraphQlApi`

If you have several APIs in the same stack, (your `appSync` config is an array), it should be `Ref::YourApiGraphQlApi` (where `YourApi` is the `name` of your api)
(see https://github.com/sid88in/serverless-appsync-plugin/blob/master/index.js#L603)

Simply reference that in a variable environment and use it in your functions normally.

For example
````yaml
environment:
  API_URL: Ref::GraphQlApi
````

Note that there is also a handy [Output Reference](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-cloudformation-outputs) Variable that contains your api url as well:

it is named: `GraphQlApiUrl` (or `YourApiGraphQlApiUrl` in multi api mode).
You can reference it like so:
````yaml
'Fn::ImportValue': GraphQlApiUrl
````

See https://github.com/sid88in/serverless-appsync-plugin/blob/master/index.js#L616

does that help?

**Comment by morgler** [comment]
Thanks. However, I struggle with using the API_URL not on the server side, but in my client code (which does not know about serverless.yml). How can I communicate this URL to the client JS application? Or should I set the API_URL on the client manually after first deploy?
