### ISSUE TITLE
ApiKeyValidityOutOfBoundsException when trying to update

### ISSUE THREAD

**Issue by Kalm004** [sid88in/serverless-appsync-plugin#202]
Hi,

When trying to update the schema of an AppSync instance (just after creating it for the first time), I'm getting the following error:

```
An error occurred: GraphQlApiKeyDefault - API key can be valid for a maximum of 365 days. (Service: AWSAppSync; Status Code: 400; Error Code: ApiKeyValidityOutOfBoundsException; Request ID: 378ebc03-1b08-11e9-9dc3-f5b7806875cf).
```

Do you have any idea of what could be happening?

Thanks.

**Comment by geblanga** [comment]
Same error message popped up while i was trying to update the stack.
From what i can figure out, API key "Expire" timestamp that is generated when you "sls deploy" is more in the future then 365 days. 
I don't have solution, but have found a workaround. So, i've ran the "sls deploy" once unsuccessfully to generate ".serverless" folder. Then I've manually changed the the timestamp in json file to something like  "1577146466" (Tuesday, December 24, 2019 12:14:26 AM). Next, ran "sls deploy -v -s development -p --aws-profile default --force" from .serverless folder (-p will skip the packaging step and --force will force the deployment). After that deploy with update passed ok.

**Comment by Kalm004** [comment]
Thanks @geblanga, I found the problem.
The API Key is created with an expiration date of exactly 365 days after the current moment in the date and time of your local computer. In my case, my local time was 1 minute in the future and that was causing the problem.
