### ISSUE TITLE
Substitutions per resolver

### ISSUE THREAD

**Issue by deankostomaj** [sid88in/serverless-appsync-plugin#208]
It would be a really nice feature if we could set substitutions for each resolver separately.

**My use case**
I'm working with DynamoDB and I want to create my resolvers as generic as possible. For example when I fetch user from database I would like to fetch also country that they are from. In my database user looks like this:
```
{ 
  partitionKey: 'user_1',
  sortKey: 'user_1',
  id: 1, 
  name: 'John', 
  countryId: 1 
}
```
My country looks like this:
```
{ 
  partitionKey: 'country_1',
  sortKey: 'country_1',
  id: 1, 
  name: 'Slovenia' 
}
```
My GQL schema looks like this:
```
type User {
  id: String
  name: String
  country: Country
}

type Country {
  id: String
  name: String
}
```
To fetch country of a my user I need to set resolver for `User.country` field. Because I can not access GQL field name that is requested in query it would be really useful if we could set `substitutions` per resolver so we would be able to use one resolver for each such occasion that would look something like this:
```
#set($relationName = "$substitution") ## this would be in this example 'country'
#set($id = "Id")
#set($field = "$relationName$id")
#set($realtionId = "${ctx.source[$field]}")
#set($concat = "_")

{
    "version" : "2017-02-28",
    "operation" : "GetItem",
    "key" : {
    	"partitionKey": { "S": "$relationName$concat$realtionId" },
        "sortKey": { "S": "$relationName$concat$realtionId" },
    }
}
```

**Comment by tezqa** [comment]
I need this improvement too. I have a local resolver used to resolve a field with its translation, stored in another field (used for the back office).

```
{
    "version": "2017-02-28",
    #set($language = $ctx.request.headers['Accept-Language'])
    #set($field = "name")
    #set($i18n = "I18n")
    #if(!$language)
    	#set($language = "en")
    #end
    "payload": "$ctx.source["$field$i18n"][$language]"
}
```

I need to create a mapping template for each field, but it would be great to have a unique template with a substitution for the field variable.

**Comment by bboure** [comment]
This seems like a feature we could implement.
Anyone wants to open a PR?
