### ISSUE TITLE
Substitution bug

### ISSUE THREAD

**Issue by deankostomaj** [sid88in/serverless-appsync-plugin#209]
As discussed in #120 substitutions are not working as expected. Substitutions in resolvers can be only referenced by `$variableName` and fail to work with `${variableName}` references. If the later example if used an error is thrown saying:
`The CloudFormation template is invalid: Template error: instance of Fn::Sub references invalid resource attribute ctx.args.exercises`.

**Comment by shahzaibmuneeb** [comment]
yeah wtf

**Comment by deankostomaj** [comment]
This bug is fixed and is waiting to be merget. #214

**Comment by bboure** [comment]
Fixed by #214
