### ISSUE TITLE
Initial feature draft

### ISSUE THREAD

**Issue by nikgraf** [sid88in/serverless-appsync-plugin#21]
On ‘serverless deploy’ it creates or updates the appsync schema. I suggest by default it uses the file ‘schema.graphql’ located in the root of the project. 

Optionally the location of the schema file can be changed with a parameter nested in the custom section in serverless.yml. A possible name could be ‘graphqlSchema’

The API calls should happen after the new resources and functions are deployed so they can be referenced and it doesn’t happen that a schema goes live that doesn’t have the necessary resources up & running.

On ‘serverless remove’ the appsync schema is removed as well. Here it happens before the cloudformation stack is removed.

Note: I don’t know to much about the mappings yet. Will read up on them and we can extend/update/correct this initial draft.

**Comment by jpstrikesback** [comment]
So to confirm this plugin handles custom AppSync config for:
- GraphQL Schema
- Data Sources
- Resolver Mappings between the schema and those data sources

and leaves Resource creation (DynamoDB, ElasticSearch, Lambda) to the serverless.yml config, does that sound right?

**Comment by sid88in** [comment]
correct

**Comment by ajagnanan** [comment]
It looks like the plugin always creates an endpoint currently. Are there plans to include updating an existing one?

**Comment by sid88in** [comment]
@ajagnanan that's correct. We do plan to add it in future but if you want, we can work together to include this feature. Is it something you would be interested in contributing?

**Comment by ajagnanan** [comment]
oh man, if you could set it up the way you think it should work I'll be able to assist

**Comment by sid88in** [comment]
lets think about it, can you please send me an email - sid88in@gmail.com and I can start a thread. thanks
