### ISSUE TITLE
Using API_KEY, stack output does not include key information

### ISSUE THREAD

**Issue by localredhead** [sid88in/serverless-appsync-plugin#212]
It seems that the deploy is successful and key is created if I log into the AWS console it's there.

Here is my stack output...

```
Serverless: Stack update finished...
Service Information
service: lambda-api
stage: dev
region: us-east-1
stack: lambda-api-dev
api keys:
  None
endpoints:
  GET - https://....amazonaws.com/dev/get
functions:
  getTable: lambda-agora-dev-getTable
layers:
  None
Serverless: Removing old service artifacts from S3...
```

**Comment by bboure** [comment]
@localredhead  I believe this info tha tis showing is referring to API gateway endpoints and api keys, and NOT to app sync endpoints/api keys.

This plugin currently does not outputs information about the created resources.
This is probably an useful improvement that could be done though.

**Comment by localredhead** [comment]
@bboure thank you for the quick response!

I asked because I saw mention of printing the API_KEY in the stack outputs here:  https://github.com/sid88in/serverless-appsync-plugin#-migration-from-versions-prior-to-10

It would be incredibly useful information to have in the stack output!

**Comment by bboure** [comment]
@localredhead I just opened a PR that implements this: #217

**Comment by localredhead** [comment]
Awesome!   PR looks great!
