### ISSUE TITLE
appSync property `authenticationType` is missing or invalid

### ISSUE THREAD

**Issue by snolangps** [sid88in/serverless-appsync-plugin#223]
While using the Multiple APIs option, I'm getting an error that looks like `appSync property 'authenticationType' is missing or invalid`, yet I didn't updated my "authenticationType: AMAZON_COGNITO_USER_POOLS" property. I only moved them _from an object, to an array of objects_ per the docs (https://github.com/sid88in/serverless-appsync-plugin#multiple-apis).

I might be missing something, but does the "authenticationType" property change a bit, or do I have to do something different in order to provide the correct value when using Multiple APIs?

Thx, snolan

**Comment by bboure** [comment]
Hi @snolangps 
It's a bug. The piece of code that checks for `authenticationType` is expecting an object and does not take into consideration that the appsync config might be an array: https://github.com/sid88in/serverless-appsync-plugin/blob/master/get-config.js#L13

Same for the following validations as a matter of fact.

If the config comes as an array, then these asserts should be wrapped in loop.
I'll have the same issue as I am right now building a multi api as well.

If you feel like fixing it and submitting a PR, that would be great.

**Comment by snolangps** [comment]
@bboure I'll definitely look at that, thx for the quick response.

**Comment by snolangps** [comment]
@bboure after pulling the repo down and writing a test for it `get-config.js`, it looks like it checks for the `config.constructor === Array` and iterates over that, and the snapshot seems to be passing. I'm currently using v1.0.1 and i see that you're up to v1.1.0. Not sure how much of the logic changed between those, but might have something to do with it... Sorry for the time wasted if it is a version issue.

**Comment by bboure** [comment]
great, @snolangps can we close this issue then?

**Comment by snolangps** [comment]
Yes, we can close this, confirmed it works now. Thank you!

**Comment by se02951** [comment]
> Yes, we can close this, confirmed it works now. Thank you!

Hi @snolangps  can u give me your get-config.js file? Thank you!
