### ISSUE TITLE
Serverless AppSync Plugin - New Features Blog

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#229]
In progress - to be published soon. We are planning to talk about the following features in the blog:

1. AppSync Offline Support.
2. Auto generated Roles and Policies
3. RDS Data Source Support
4. Pipeline Resolvers Support
5. Multiple API Support
6. External Data Source and Mapping Template Reference
7. Simplified Data Source Config
8. Default Filename conventions for mapping template.
9. Enhanced stack output.
10. Merge GraphQL Schemas Support.

We will mention the name of the authors and include their PR's in the post to give due credit. Please let us know if you have any thoughts or if we missed adding your feature :) If you have some existing write up about your feature please feel free to share 4-5 line summary. 

cheers
Sid and Benoit

**Comment by bboure** [comment]
Published here https://medium.com/hackernoon/serverless-appsync-plugin-top-10-new-features-3faaf6789480
