### ISSUE TITLE
schema stitching

### ISSUE THREAD

**Issue by bboure** [sid88in/serverless-appsync-plugin#230]
We recently merged #227 which adds a great addition to the plugin.
However, I just realized that it relies on a deprecated package: https://github.com/okgrow/merge-graphql-schemas

I suggest, we refactor the PR and use [Appolo Stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html) instead.

@trilliput would you have time to have a look at this?

**Comment by trilliput** [comment]
Sorry, I've missed, that merge-grahpql-schemas is deprecated. I'll take a look. No EDD yet.

**Comment by bboure** [comment]
👍  Let us know if we can help

**Comment by trilliput** [comment]
@bboure I'll definitely do it, feel free to assign the issue to me. I'm just not sure when exactly. Approximately this weekend.

**Comment by trilliput** [comment]
@bboure How far are you with integrating Amplify CLI https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-category-api? It looks promising and if you're already working on integrating it, we might avoid one more intermediate step and concentrate our efforts on Amplify CLI. I'd be glad to help here as well.

**Comment by bboure** [comment]
@trilliput There is no integration to Amplify CLI on the roadmap yet

There are definitely things that we could explore and that were discussed already, like [GraphQL Transformation](https://aws-amplify.github.io/docs/cli/graphql?sdk=js), for generating resources, data sources and mapping templates.

https://github.com/sid88in/serverless-appsync-plugin/issues/62
https://github.com/sid88in/serverless-appsync-plugin/issues/211
https://github.com/sid88in/serverless-appsync-plugin/issues/151

There is also [Codegen](https://aws-amplify.github.io/docs/cli/codegen?sdk=js)

Maybe we could use it somehow under the hood to auto generate
- [Statements](https://aws-amplify.github.io/docs/cli/codegen#amplify-codegen-statements-)
- [types](https://aws-amplify.github.io/docs/cli/codegen#amplify-codegen-types-)


Optionaly, we could add something on top of AWS-cli that does the equivalent of `amplify api gql-compile` in the package you are refering to, but for serverless (this plugin).

All ideas and PRS are welcome :)

**Comment by jasonlimantoro** [comment]
Does this mean we cannot use the `extend` keyword used in Apollo Stitching?

**Comment by vicary** [comment]
I believe we basically need this to convert Apollo schemas into AppSync version.

Dug very deep on Sunday and made [`appsync-schema-converter`](https://www.npmjs.com/package/appsync-schema-converter).

I don't think I can finish it on my own, looking for contributors to cover all directives and edge cases.

**Comment by bboure** [comment]
Closing this issue as `merge-graphql-schemas` is now back into maintenance...
... And Apollo deprecated their own Schema Stitching ¯\\\_(ツ)_/¯
