### ISSUE TITLE
Error: Relational database type is not supported

### ISSUE THREAD

**Issue by harleyguru** [sid88in/serverless-appsync-plugin#232]
I've followed the exact steps to link RDS DB cluster as a data source.
But I am getting that it's not supported type as you can see here:
![Screen Shot 2019-03-20 at 6 48 44 PM](https://user-images.githubusercontent.com/35247645/54704176-ed241380-4b42-11e9-93ee-b70f8e1e56f5.png)

This is my template:
![Screen Shot 2019-03-20 at 6 48 54 PM](https://user-images.githubusercontent.com/35247645/54704200-f7dea880-4b42-11e9-9258-41c080615de2.png)

**Comment by harleyguru** [comment]
oh sorry, I didn't upgrade plugin.

**Comment by harleyguru** [comment]
Hi @sid88in I've deployed successfully for RDS data source, but in the console I could notice AppSync set nothing for RDS cluster Arn.

Instead of dbClusterIdentifier, should I set DB Cluster Arn?

**Comment by roznalex** [comment]
@harleyguru does it work with the DB Cluster Arn instead?

**Comment by harleyguru** [comment]
hi @roznalex didn't try it yet.

**Comment by roznalex** [comment]
@harleyguru fixed the issue in the [PR](https://github.com/sid88in/serverless-appsync-plugin/pull/234). After the PR will be merged, it should work fine with the "dbClusterIdentifier" config.

**Comment by harleyguru** [comment]
Thanks @roznalex Could you let me know when it's merged and ready to use please?

**Comment by tracstarr** [comment]
So I've been trying recently to get this to work. Using  _DbClusterIdentifier_ with the ref as defined in the docs  does not correctly set the RDS Cluster ARN. I am forced to manually modify the cluster ARN via console dropdown. 

I am using  "serverless-appsync-plugin": "^1.1.1". The _DbClusterIdentifier_ also doesn't set the ARN correctly, it only uses the ClusterName. I had to use

_dbClusterIdentifier: "arn:aws:rds:#{AWS::Region}:#{AWS::AccountId}:cluster:${self:service.name}-${self:custom.stage}"_

My ClusterDefinition

 AuroraRDSCluster:
      Type: "AWS::RDS::DBCluster"
      Properties:
        MasterUsername: ${self:custom.AURORA.USERNAME}
        MasterUserPassword: ${self:custom.AURORA.PASSWORD}
        DBSubnetGroupName:
          Ref: AuroraSubnetGroup
        Engine: aurora
        EngineVersion: "5.6"
        EngineMode: serverless
        DatabaseName: ${self:custom.AURORA.DB_NAME}
        BackupRetentionPeriod: 1
        DBClusterIdentifier: sls-test-${self:custom.stage}
        DBClusterParameterGroupName:
          Ref: AuroraRDSClusterParameter
        VpcSecurityGroupIds:
          - Fn::GetAtt: ServerlessVPC.DefaultSecurityGroup
        ScalingConfiguration:
          AutoPause: true
          MaxCapacity: 4
          MinCapacity: 1
          SecondsUntilAutoPause: 300


Additionally, the automatic permissions/role that's created doesn't work anymore. it needs to be the following as defined in aws docs

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "SecretsManagerDbCredentialsAccess",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetSecretValue",
                "secretsmanager:PutResourcePolicy", // unnecessary
                "secretsmanager:PutSecretValue", // unnecessary
                "secretsmanager:DeleteSecret", // unnecessary
                "secretsmanager:DescribeSecret", // unnecessary
                "secretsmanager:TagResource" // unnecessary
            ],
            "Resource": "arn:aws:secretsmanager:*:*:secret:rds-db-credentials/*"
        },
        {
            "Sid": "RDSDataServiceAccess",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:CreateSecret", // unnecessary
                "secretsmanager:ListSecrets", // unnecessary
                "secretsmanager:GetRandomPassword", // unnecessary
                "tag:GetResources", // unnecessary
                "rds-data:BatchExecuteStatement",
                "rds-data:BeginTransaction",
                "rds-data:CommitTransaction",
                "rds-data:ExecuteStatement",
                "rds-data:RollbackTransaction"
            ],
            "Resource": "*"
        }
    ]
}
