### ISSUE TITLE
The schema property does not work

### ISSUE THREAD

**Issue by ntrp** [sid88in/serverless-appsync-plugin#237]
I am trying to move the schema location to a subdirectory and it seems like it does not work. I have the current setup:
```
custom:
  ...
  appSync:
    ...
    schema: appsync/schema.graphql
```

The error I get is: 

`Serverless: ERROR: Error: schema file: /<project_location>/schema.graphql must exist
`

where project_location is the actual path.. I tried also wrapping into quotes but didn't work.

**Comment by ntrp** [comment]
I actually just found the reason why it is happening, the schema property is taken from:
```
custom:
  ...
  appsync-offline:
    schema: appsync/schema.graphql
```
instead of 
```
custom:
  ...
  appSync:
    ...
    schema: appsync/schema.graphql
```
is that normal or it's not intended?

**Comment by bboure** [comment]
@ntrp What are you trying to do when the error occurs? deploying or run sls offline?

**Comment by ntrp** [comment]
Offline, I think I get your argument but in my opinion the schema location should always be in one location.

**Comment by bboure** [comment]
@ntrp this is an issue for https://github.com/aheissenberger/serverless-appsync-offline then I guess.
The default should come from the appSync config.
A workaround would be to put the path in a variable in `custom` and reference it from both configs.

**Comment by ntrp** [comment]
Ah ok, well then we can close it.
