### ISSUE TITLE
Multiple Authorization Types with an AWS AppSync Endpoint

### ISSUE THREAD

**Issue by lukasf98** [sid88in/serverless-appsync-plugin#241]
Multiple Authorization Types with an AWS AppSync Endpoint was just added to AppSync. Could you please add the possibility to configure those with the serverless-appsync-plugin.

https://github.com/aws/aws-appsync-community/issues/1

**Comment by bboure** [comment]
@lukasf98 It seems like they are rolling it out at the moment.
Let's wait a day or 2 to see when it gets announced and put our hands on the doc.

**Comment by jimmyn** [comment]
looking forward to seeing this feature!

**Comment by danielbayerlein** [comment]
AWS AppSync Now Supports Configuring Multiple Authorization Types for GraphQL APIs: https://aws.amazon.com/de/about-aws/whats-new/2019/05/aws-appsync-now-supports-configuring-multiple-authorization-type/
