### ISSUE TITLE
additionalAuthenticationProviders not working

### ISSUE THREAD

**Issue by mfernand0** [sid88in/serverless-appsync-plugin#250]
Hi everyone... so I'm trying to user both, cognito and openid with no luck, the additional provider never gets to work.

I guess **additionalAuthenticationProviders** is not working at all, any comment or does anybody get it to work?

thanks

**Comment by bboure** [comment]
@mfernand0 what version of the plugin are you using?
I have used it recently and did not encounter any issue.
Could you share your `serverless.yml` file?

**Comment by mfernand0** [comment]
thanks man, I only update the version and indeed is working fine.. my bad!
