### ISSUE TITLE
Update already created API

### ISSUE THREAD

**Issue by Frikitrok** [sid88in/serverless-appsync-plugin#251]
HI, in my use-case we already have production AppSync API with endpoint, and i want to write CI/CD to it with this plugin.

 I wrote everything and it works fine when deploying from scratch, but is there a way to update already created API (by hands, there no cf stack for it) to save API endpoint?

Because our clients hard coded it in theirs applications and would be rly hard to make soft transition to new API endpoint.
I already implement such thing with only cloud formation (just put API id in every handler/datasource/schema and do not put GraphQlApi resource at all) but it looks more ugly/complicated

**Comment by bboure** [comment]
@Frikitrok This plugin, just as Serverless Framework, rely on cloudformations in order to deploy the resources. 
The is no way to update existing resources that were created manually.

My advice would be to create a new stack from scratch, change any consumer to use the new stack, then destroy the old API.

**Comment by Frikitrok** [comment]
@bboure i just not sure if i only one collide to this problem, but maybe it is possible to add smthing like APIid parameter, and if it set, sls won't create new API but will update the one specified in this parameter?

**Comment by Frikitrok** [comment]
I think this is AWS problem, just split endpoint address and API itself will solve the problem. In case someone by mistake delete API there is no way to restore it endpoint. But for now i should search workaround for this issue
