### ISSUE TITLE
How to use an existing appsync

### ISSUE THREAD

**Issue by manpirez** [sid88in/serverless-appsync-plugin#260]
I have the appsync resource previously created and I want to add configuration with serverless framework but always create a new resource, how can I use an existing one?

Thank you

**Comment by bboure** [comment]
@manpirez You cannot update an existing appsync stack that was created manually.
What you can do is deploy a new stack and switch your existing infrastructure to use the new one, when it is created.
Then you can delete the old AppSync Api

**Comment by manpirez** [comment]
Thanks @bboure
