### ISSUE TITLE
Why releases are not being publish since June 2019

### ISSUE THREAD

**Issue by moacirosa** [sid88in/serverless-appsync-plugin#272]
Is `master` your stable branch? If so, is there any special reason _(instability, lack of time, approval process...)_ to not release, in both, _GitHub_ and _npm repository_? As I could see there aren't new releases since _June 01st_ when [1.1.2](https://www.npmjs.com/package/serverless-appsync-plugin/v/1.1.2) was launched. I was particulary interested in #247 that was already merged but not released.

> Congratulations for the cool project & hard work :clap:

**Comment by moacirosa** [comment]
Looks like #247 is related exactly with this same issue.

**Comment by bboure** [comment]
Hi @moacirosa 
Well, you probably nailed it with *lack of time*. At least, as far as I am concerned. 
I have been busy with other stuff recently but I am recently slowly coming back to my initial projects implying this plugin.
I promise I will try to find some time to review/test/approve/merge anything that is pending.
I'll also try to get in touch with @sid88in and discuss with him what should be our next moves.

Thank you for being patient.

**Comment by moacirosa** [comment]
Awesome! Thanks for the feedback and congratulations for the project and time dedicated to open source :clap:
