### ISSUE TITLE
Appsync Resolver Caching

### ISSUE THREAD

**Issue by michaelrhoden** [sid88in/serverless-appsync-plugin#276]
Appsync now has built in caching capability, at a full api level, and more interesting, at a resolver level. Curious if anyone is working on getting this working within this plugin? I think adding the ability to annotate that a resolver should cached and a TTL (60-3600 seconds) is supported.

Reference:
https://aws.amazon.com/blogs/mobile/appsync-caching-transactions/

**Comment by bboure** [comment]
Thanks @michaelrhoden 
This is a really cool new feature that we definitely should implement. 
There is nothing planned yet on this.
You are welcome to open a PR if you want to spend some time on this.

**Comment by bboure** [comment]
Please see #288
