### ISSUE TITLE
Automatically generate Graphql services ?

### ISSUE THREAD

**Issue by hvoyer** [sid88in/serverless-appsync-plugin#289]
Question: AppSync allows generating graphql services for creating, updating, searching and deleting an object.
This is found in AWS AppSync > [name of your app] > Schema > Create Resources.
Is it possible to activate this option when deploying?

[https://www.dropbox.com/s/7i8051ldhf6nv5g/2019-12-15_18-08-58.png?dl=0](url)

**Comment by bboure** [comment]
Hi @hvoyer 
This is currently no supported by the plugin, and it sounds a bit tricky.
First, I don't think that CloudFormation or AppSync's API support that use case.
It sounds like a Console feature/helper. 

Then, this is probably the opposite of what you want. What I mean is that you probably want to first define your GraphQl schema, and through annotations, generate your dataSources (dynamodb tables, for example).
This plugin does not currently support that feature either (yet), but it is something that we are [considering to implement](https://github.com/sid88in/serverless-appsync-plugin/issues/211) in this plugin

note: You might want to have a look at [amplify-cli](https://github.com/aws-amplify/amplify-cli) that supports [the feature I just mentioned](https://aws-amplify.github.io/docs/cli-toolchain/graphql).

**Comment by hvoyer** [comment]
Hi @bboure 
The support for @model is more and better than expected.
If this is the case, Is there a bounty so I can chip in. 
Thanks,
>  A single @model directive configures the following AWS resources:
> 
> An Amazon DynamoDB table with PAY_PER_REQUEST billing mode enabled by default.
> An AWS AppSync DataSource configured to access the table above.
> An AWS IAM role attached to the DataSource that allows AWS AppSync to call the above table on your behalf.
> Up to 8 resolvers (create, update, delete, get, list, onCreate, onUpdate, onDelete) but this is configurable via the queries, mutations, and subscriptions arguments on the @model directive.
> Input objects for create, update, and delete mutations.
> Filter input objects that allow you to filter objects in list queries and connection fields.
