### ISSUE TITLE
Unable to test pipeline resolver in local

### ISSUE THREAD

**Issue by chaitanya11** [sid88in/serverless-appsync-plugin#299]
Since appsync emulator don't have support of pipeline resolver (https://github.com/ConduitVC/aws-utils/issues/59), i am unable to to test pipeline resolver in local. Can Some one suggest some alternative methods to test pipeline resolver in local?.

**Comment by bboure** [comment]
The emulator is deprecated.
Check this out https://github.com/bboure/serverless-appsync-simulator

It supports pipeline resolvers

**Comment by chaitanya11** [comment]
@bboure  thanks for the response. I tried with your plugin, but got some issue.
i have raised and issue https://github.com/bboure/serverless-appsync-simulator/issues/14 , can you have a look at it.

**Comment by bboure** [comment]
Resolved in https://github.com/bboure/serverless-appsync-simulator/issues/14
