### ISSUE TITLE
Enable AWS X-Ray on AppSync APIs not working

### ISSUE THREAD

**Issue by rolwincrasta** [sid88in/serverless-appsync-plugin#314]
After using xrayEnabled: true, the AWS X-Ray does not seem to be enabled.

I already had a AppSyc application running, i went ahead and Added xrayEnabled: true, so it did not give any errors on SLS Deploy, however it did not enable X-Ray.

So is this config not applicable to an existing AppSync

**Comment by bboure** [comment]
@rolwincrasta the current release does not include X-Ray feature yet. 
We'll try to publish a new release soon that includes it.
X-ray is available on the master branch. If you want to use this feature, you can point the the master branch

**Comment by Sunac** [comment]
This one should be closed as v1.3.0 covers it.
Just bump up the version and include it in your serverless
`appSync:
    authenticationType: API_KEY
    ...
    xrayEnabled: true //this line`

**Comment by bboure** [comment]
Thank you @Sunac 
I'll close this it
