### ISSUE TITLE
Function names prefixed with "GraphQlFunctionConfiguration"

### ISSUE THREAD

**Issue by tsmith-rv** [sid88in/serverless-appsync-plugin#321]
All of my Appsync function names are prefixed with `GraphQlFunctionConfiguration` once they're created in AWS. From the code in the plugin, it looks like this is intended behavior. Is there a specific reason for this? I wouldn't mind opening a PR to remove the prefix if everyone was open to that, but my assumption is that this exists for a reason, or maybe you can create the function without a prefixed name and I'm just missing it.

My YML
```yml
- name: GetActiveLinksByLocation
  dataSource: GetActiveLinksByLocation
```

Expected function name in AWS: `GetActiveLinksByLocation`
Actual function name in AWS: `GraphQlFunctionConfigurationGetActiveLinksByLocation`

**Comment by bboure** [comment]
Hi @tsmith-rv  Thank you for bringing this to our attention.

All resource names come with a prefix in order to avoid clashes in names. 
It looks like [here](https://github.com/sid88in/serverless-appsync-plugin/blob/master/src/index.js#L875) we are using the Resource Name as the function name. It looks like a mistake to me, and I guess it could be removed.

I just wonder what impact this could have on backward compatibility. I don't feel like it should be an issue.

We would be happy to accept a PR that removes it if you can test and confirm that it does not break existing stacks.

**Comment by tsmith-rv** [comment]
> Hi @tsmith-rv Thank you for bringing this to our attention.
> 
> All resource names come with a prefix in order to avoid clashes in names.
> It looks like [here](https://github.com/sid88in/serverless-appsync-plugin/blob/master/src/index.js#L875) we are using the Resource Name as the function name. It looks like a mistake to me, and I guess it could be removed.
> 
> I just wonder what impact this could have on backward compatibility. I don't feel like it should be an issue.
> 
> We would be happy to accept a PR that removes it if you can test and confirm that it does not break existing stacks.

On it!

**Comment by tsmith-rv** [comment]
I'm about to open the PR now. It works well. It basically just seems to treat it as a normal function renaming operation. Normally when you rename an Appsync function, as the stack updates, you temporarily have two functions (the original and a new one with the updated name) and as long as everything is successful with the stack update, it switches to the new one and deletes the old one. 

Like this (before I updated the code):

Original Function
<img width="1258" alt="Screen Shot 2020-04-10 at 11 06 21 PM" src="https://user-images.githubusercontent.com/39560403/79033979-a7d4e880-7b80-11ea-9b97-1001d0d9096b.png">

During Stack Update
<img width="1255" alt="Screen Shot 2020-04-10 at 11 07 31 PM" src="https://user-images.githubusercontent.com/39560403/79034003-d2bf3c80-7b80-11ea-861c-61f8e7355e2f.png">

After Stack Completes Successfully
<img width="1249" alt="Screen Shot 2020-04-10 at 11 07 43 PM" src="https://user-images.githubusercontent.com/39560403/79034017-e9fe2a00-7b80-11ea-9277-c9151e6325b7.png">

After I update the code, it looks like:

Original Function
<img width="1249" alt="Screen Shot 2020-04-10 at 11 07 43 PM" src="https://user-images.githubusercontent.com/39560403/79034025-fa160980-7b80-11ea-809b-636473c3d768.png">

During Stack Update
<img width="1254" alt="Screen Shot 2020-04-10 at 11 09 04 PM" src="https://user-images.githubusercontent.com/39560403/79034028-04d09e80-7b81-11ea-83dd-f6ed01bef297.png">

After Stack Completes Successfully
<img width="1253" alt="Screen Shot 2020-04-10 at 11 09 11 PM" src="https://user-images.githubusercontent.com/39560403/79034031-0b5f1600-7b81-11ea-8ea3-02a991beca50.png">

**Comment by tsmith-rv** [comment]
I'm about to open the PR now. It works well. Originally, I thought it treated it as a normal renaming operation. Normally when you rename an Appsync function, as the stack updates, you temporarily have two functions (the original and a new one with the updated name) and as long as everything is successful with the stack update, it switches to the new one and deletes the old one.

Like this (before I updated the code):

Original Function
<img width="1258" alt="Screen Shot 2020-04-10 at 11 06 21 PM" src="https://user-images.githubusercontent.com/39560403/79033979-a7d4e880-7b80-11ea-9b97-1001d0d9096b.png">

During Stack Update
<img width="1255" alt="Screen Shot 2020-04-10 at 11 07 31 PM" src="https://user-images.githubusercontent.com/39560403/79034003-d2bf3c80-7b80-11ea-861c-61f8e7355e2f.png">

After Stack Completes Successfully
<img width="1249" alt="Screen Shot 2020-04-10 at 11 07 43 PM" src="https://user-images.githubusercontent.com/39560403/79034017-e9fe2a00-7b80-11ea-9277-c9151e6325b7.png">

But that isn't actually what happens when updating the package to the one with the code update. Doing that seems to just rename the Appsync functions in place. It doesn't create a new function and switch over — it just renames the existing function.

After I update the code, it looks like:

Original Function
<img width="1249" alt="Screen Shot 2020-04-10 at 11 07 43 PM" src="https://user-images.githubusercontent.com/39560403/79034025-fa160980-7b80-11ea-809b-636473c3d768.png">

During Stack Update
<img width="1249" alt="Screen Shot 2020-04-10 at 11 07 43 PM" src="https://user-images.githubusercontent.com/39560403/79034025-fa160980-7b80-11ea-809b-636473c3d768.png">

After Stack Completes Successfully
<img width="1253" alt="Screen Shot 2020-04-10 at 11 09 11 PM" src="https://user-images.githubusercontent.com/39560403/79034031-0b5f1600-7b81-11ea-8ea3-02a991beca50.png">

**Comment by bboure** [comment]
@tsmith-rv Thank you for the explanation. 
What you describe makes sense. The reason is that renaming the function in the yml also renames the Logical resource Id (the name of the resource in CloudFormation).
With your change, the logical resource id is kept (as long as the function is not renamed too). What changes is the function name, as expected.
