### ISSUE TITLE
ERROR: Error: Query.getMessages defined in resolvers, but not in schema

### ISSUE THREAD

**Issue by ToufeeqP** [sid88in/serverless-appsync-plugin#327]
When I am trying to test the AppSync using offline, I am getting this error. Even though I have defined the getMessages field inside the query type. Here is query snippet from schema file: 
`type Query {
  getMessages (type: String!): [Message!]!
}`
I have defined Message type as well.

**Comment by bboure** [comment]
@ToufeeqP what offline plugin are you using?

**Comment by ToufeeqP** [comment]
https://www.npmjs.com/package/serverless-appsync-offline.

**Comment by bboure** [comment]
@ToufeeqP that plugin relies on a deprecated package (https://github.com/ConduitVC/aws-utils).
Please try https://github.com/bboure/serverless-appsync-simulator
