### ISSUE TITLE
How can I update the appsync API Endpoint path?

### ISSUE THREAD

**Issue by zhaoyi0113** [sid88in/serverless-appsync-plugin#335]
After deploy with `serverless`, a random endpoint URL is generated like:

`https://xxxxxx.appsync-api.ap-southeast-2.amazonaws.com/graphql`

I wonder how I can update the last part of this URL to be something other than `/graphql`.

**Comment by bboure** [comment]
Hi @zhaoyi0113 
This is by design in AWS AppSync. There is no way to change that except by using a CDN (cloudfront) and using your own domain.
