### ISSUE TITLE
Question: Subscription mapping templates

### ISSUE THREAD

**Issue by veloware** [sid88in/serverless-appsync-plugin#337]
What is the correct way to add a mapping template for a Subscription, where the subscription uses `@aws_describe`?  In particular what is datasource type? and what should the request and response mapping template be?

Thanks!

**Comment by veloware** [comment]
I think I may have got this sorted - 

serverless.yml
(custom-> appSync -> dataSources)
```
- type: NONE
  name: mutationSubscriptionSource
```

(custom -> appSync -> mappingTemplates)
```
- dataSource: mutationSubscriptionSource
  type: Subscription
  field: <subscription name>
```

request template - 
```
{
    "version": "2017-02-28",
    "payload": $utils.toJson($context.arguments)
}

```

response template
```
$utils.toJson($context.result)

```

look about right?

**Comment by bboure** [comment]
@veloware tWhat is `@aws_describe` ? I am not familiar with it. can you point the doc?
Your config looks good though

**Comment by bboure** [comment]
Oh, did you mean `@aws_subscribe` ?

**Comment by veloware** [comment]
Yes, sorry `@aws_subscribe`... long day.  Thanks for confirming the config, the `NONE` for datasource threw me off, i'll maybe update the docs if I get a sec to include it as one of the possible datasources, thanks
