### ISSUE TITLE
FEATURE REQUEST : Support for Direct Lambda Resolvers

### ISSUE THREAD

**Issue by kziemski** [sid88in/serverless-appsync-plugin#348]
VTL Request/Reponse Mapping is now optional.
Given the convenience feature of defaults for request response vtl, 
there probably needs to be a update to the plugin to support direct lambda resolvers, correct?

[https://aws.amazon.com/blogs/mobile/appsync-direct-lambda/](https://aws.amazon.com/blogs/mobile/appsync-direct-lambda/)

**Comment by kziemski** [comment]
Its possibly already supported in cloudformation as the properties are not required 
but would need to create some boolean option to specify direct: true as opposed to assuming default

**Comment by bboure** [comment]
Hi @kziemski 
Thanks for pointing that out. This new feature looks great. All of my Lambda templates are just the same and do almost nothing but just forwarding the response. So this would simplify a lot.

I guess the right approach is to make the templates optional for Lambdas
Currently, they already are but it defaults to `[type].[field].request.tpl` or `[type].[field].response.tpl`.

I guess we could just introduce a new option and accept `false` as a value, meaning *no template*

**Comment by bboure** [comment]
Please see #350 
Anyone willing to help testing this is welcome to do so
Thanks

**Comment by bandaot** [comment]
I think it should be better if we can set the default mapping template as false, then there is no need to set the request and response property anymore.

**Comment by bboure** [comment]
Thank you for your feedback @bandaot 
I left a comment in your commit. 
I will change my PR and inpireme with your idea of a default/global. Sounds like a good idea, even for other use cases.

**Comment by louisholley** [comment]
any idea when this fix will be merged?
