### ISSUE TITLE
Cannot write comments or descriptions on the schema

### ISSUE THREAD

**Issue by osjupiter** [sid88in/serverless-appsync-plugin#356]
I met the issue that I cant define description comments on a schema when I use this plugin.

This is because  all comments trimmed as follows.
https://github.com/sid88in/serverless-appsync-plugin/blob/e67c132e8200add9833bce793ee17b85b2beda8d/src/index.js#L840-L843

I think trimming all the # comments is too much.
If I put a comment in the enum definition, it will just be ignored by Appsync.

So  # comments should be allowed.

**Comment by bboure** [comment]
Hi @osjupiter Thanks for opening this issue.
So, what you are suggesting is that we only trim `#` comments on enums, where not supported ?
Makes sense, although it makes the rule a bit more complex.

Would you like to open a PR to fix this?

**Comment by EmiiFont** [comment]
@osjupiter @bboure 
this [PR](https://github.com/sid88in/serverless-appsync-plugin/pull/387) should address this issue

**Comment by bboure** [comment]
Yes! Thank you @EmiiFont
