### ISSUE TITLE
How to enable Encrypt/Decrypt GraphQL responses ?

### ISSUE THREAD

**Issue by Jackychans** [sid88in/serverless-appsync-plugin#358]
Hi everyone,

My backend stack is built based on Appsync+GraphQL protected by AWS Cognito User Pool consumed by some windows apps. However, there are some information returned from appsync that could be exposed by using such tools Fiddler, Charles Proxy to capture api responses (in json).

Basically, I'm looking for a solution to embed RSA keys on clients in which json responses from appsync could be encrypted over the wire and decrypted by windows apps client using secret keys. Of course, this security mechanism should be maintained separately so that developers could work normally on dev server without knowing this type of security would be enable on production server.

I want to investigate but still no idea where to get started. Any recommendation to implement above ?

**Comment by bboure** [comment]
@Jackychans What you are looking for is out of scope of this plugin which is just a helper to deploy AppSync API's.
I would recommend you to open an issue in the https://github.com/sid88in/serverless-appsync-plugin repo and ask the AppSync team about it.
