### ISSUE TITLE
The plugin keeps showing "SchemaError: Expected `schema` to be an object or boolean" no matter what

### ISSUE THREAD

**Issue by flavioescobar** [sid88in/serverless-appsync-plugin#361]
I tried to use several schema definitions to make this plugin work (even dummy sample schemas), but every time I run the plugin, I get this error.

**Comment by flavioescobar** [comment]
Wrong repo, sorry! Meant to post this on the `serverless-appsync-offline` project :)

**Comment by murribu** [comment]
@flavioescobar Did you post this error to the other repo? Did you get it resolved? I'm having the same problem.

**Comment by bboure** [comment]
@murribu @flavioescobar `serverless-appsync-offline` is based on an archived project and seems not to be maintained anymore. 
You can use https://github.com/bboure/serverless-appsync-simulator instead.
