### ISSUE TITLE
Lambda functionName does not pick up alias

### ISSUE THREAD

**Issue by vicary** [sid88in/serverless-appsync-plugin#365]
By providing `provisionedConcurrency` or `reservedConcurrency` to the function itself, serverless will create an alias for the lambda. But this plugin does not automatically pick up the generated alias/qualifiers and only connects to the $LATEST version without scaling/throttling.

Is it supposed to be able to pick it up, or is there any other ways to do it?

**Comment by bboure** [comment]
@vicary Thanks for opening this issue.
By default, if you use `functionName` the `$LATEST` alias is used.
You probably can use the `lambdaFunctionArn` param for that purpose.

I have never worked with `provisionedConcurrency` or `reservedConcurrency` and I am not sure how they use aliases. Is it a fixed value?

That being said, we probably could add a value in the lambda option for that purpose. Something like

```yml
type: AWS_LAMBDA
config:
  functionName: myLambda
  functionAlias: myAlias
```

**Comment by vicary** [comment]
@bboure the stability of the alias name is exactly what we are currently testing, but with only `provisionedConcurrency` it comes out as `provisioned`, I reasonable doubles that it being a fixed value.

I'll dig into serverless core a bit to see if we can reference it.

I guess if a reference is available I can do that via variables in `serverless.yml`, your proposed option should work for most cases!

**Comment by bboure** [comment]
Is there a plugin for provisioned concurrency?

There is probably a [AWS::Lambda::Alias](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html)

And then we probably can use the `Name` attribute

**Comment by vicary** [comment]
It's a core feature https://www.serverless.com/blog/aws-lambda-provisioned-concurrency

As a workaround, I am guessing that I can put a long chain of `Ref`s and `Fn::Join`s in AWS SAM syntax in `lambdaArn` for the moment.

**Comment by vicary** [comment]
In our own referenced script file in `serverless.yml`, we have implemented a logic to use `lambdaFunctionArn` with the `Fn::GetAtt` syntax whenever there is `provisionedConcurrency` in the lambda.

This very feature has a stable alias name as *provisioned*,

https://github.com/serverless/serverless/blob/0c2884418874079c9e8b0f8c7f508ce62f5b4599/lib/plugins/aws/lib/naming.js#L179

But I think `functionAlias` is the way to go as it serves a broader audience.

**Comment by vicary** [comment]
@bboure I have deployed a reduced version of my app and it works, all the AppSync resolvers are now pointing to the generated alias ARN.

![image](https://user-images.githubusercontent.com/85772/100097498-8b7b8700-2e97-11eb-973a-30d535b6a1d7.png)

I have created a PR for that.
