### ISSUE TITLE
Guest Users

### ISSUE THREAD

**Issue by mkarsene** [sid88in/serverless-appsync-plugin#386]
Hi,
I have already setup a userpool for authenticated users. However, I also need to have guest users. Is there a way to do this. For instance, if I use the Amplify Framework. I can create IAM auth with an identity pool for guest/public users and then a userpool for aunthenticated users. Then in my graphql schema, I can create rules which specify the rights of the different users. Is there a way to do this here?

**Comment by bboure** [comment]
Hi,

Yes, you need 2 authentication methods:
- Cognito
- IAM

Check the yml example in the README to understand how it can be achieved. 

For authenticated users, you use identity pools unauthenticated as you mentioned.

The next step is to use the [@aws_auth]()https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html directives in your schema.
