### ISSUE TITLE
Use buildASTSchema for validation

### ISSUE THREAD

**Issue by AleksaC** [sid88in/serverless-appsync-plugin#402]
From what I can see the validation of graphql schema is done by parsing it, which seems to only check the syntax of the schema and not the semantics. This means that a lot of issues are not caught during validation. The worst of those are errors in auth directives. 

For example I forgot `aws` prefix in `@aws_cognito_user_pools` directive and it passed the validation and got deployed without errors. The problem is that it basically does the opposite of what it's supposed to do, i.e. my query was available using standard api key authentication and threw an error when authenticated with cognito. Another issue is that typos in types also pass validation but the error is thrown later during deployment, which is better but still not ideal.

I looked around for a bit and found that [`buildASTSchema`](https://graphql.org/graphql-js/utilities/#buildastschema) properly validates the schema if stubs for AWS scalars and directives are added (I tested with [python port](https://github.com/graphql-python/graphql-core) of graphql-js, but it should work the same way in the js version; also to make it clear, the stubs are added in validation code not the schema that needs to be validated).  This of course means that if this was to be added the stubs have to be maintained and maybe even an option to fall back to previous validation needs to be added (i.e. `validateSyntaxOnly`).

If you don't quite understand what I'm referring to I can create and link an example that demonstrates this. If I made myself clear enough in this issue and you are open to this change, I could also submit a PR for this when I get time to work on it, which should be withing a couple of days.

**Comment by bboure** [comment]
Thank you @AleksaC 

I think I see what you mean and it sounds like a good improvement. Feel free to implement it when you have some time.

Thank you!
