### ISSUE TITLE
Unable to deploy on windows - Schema Creation Status is FAILED

### ISSUE THREAD

**Issue by menser-fivetalent** [sid88in/serverless-appsync-plugin#404]
Have been unable to deploy on windows (currently using gitbash or powershell)

The exact same code is deploying fine using osx.

I have verified that this same behavior is reproducible with the example in this repo and a completely new serverless project adding the bare minimum for serverless-appsync-plugin.

```
Serverless Error ----------------------------------------

  An error occurred: GraphQlSchema - Schema Creation Status is FAILED with details: Found 1 problem(s) with the schema:
  The operation type 'Query' is not present when resolving type 'query' [@3:1]..
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.12.0
     Framework Version:         2.35.0
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.3
```

When comparing the working cloudformation stack template from OSX to the failed template from windows they are identical. 

I have tried yarn and npm to install packages. We have been using serverless-appsync-plugin for a while successfully but failing on a new project. I took the node_modules directory off another windows machine on an older project and replaced the one in the new project and it appears to deploy. However, there are so many differences between the two folders that it's taking a long time to track down which is causing the issue.

Attached is a simple project that fails:
[serverless-appsync-windows-fail.zip](https://github.com/sid88in/serverless-appsync-plugin/files/6332385/serverless-appsync-windows-fail.zip)

**Comment by menser-fivetalent** [comment]
It would appear that because the older project was built when the max version was 1.6.0 that is why copying node_modules works.

If I lock the project at 1.6.0 it appears to work. 

I have not compared any newer version currently. However it would appear that something added after 1.6.0 is what is breaking windows.

**Comment by bboure** [comment]
@menser-fivetalent Can you pinpoint the exact version that breaks it? Does it break already at 1.7.0?

**Comment by menser-fivetalent** [comment]
> @menser-fivetalent Can you pinpoint the exact version that breaks it? Does it break already at 1.7.0?

It would appear the issue was introduced in version 1.9.0.

**Comment by bboure** [comment]
@menser-fivetalent I was expecting that. 

I am pretty sure [this PR](https://github.com/sid88in/serverless-appsync-plugin/pull/399) introduced the problem.

I believe that the [globby](https://www.npmjs.com/package/globby) might be creating some issues.

They recently fixed [an issue](https://github.com/sindresorhus/globby/pull/171) but I checked and it is included in this plugin. 

Could you try debugging around [these lines](https://github.com/sid88in/serverless-appsync-plugin/blob/master/src/get-config.js#L69-L71) and maybe try to figure out what is going on?

Unfortunatlly I do not have a windows machine.
