### ISSUE TITLE
CLI is returning error in multiple projects

### ISSUE THREAD

**Issue by joaocostamm** [sid88in/serverless-appsync-plugin#405]
Multiple project that uses serverless to deploy AppSync is finishing in a CLI error:
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessAppsyncPlugin for "clientId", "username", "password", "jwtToken", "apiKey", "port"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
AppSync Plugin: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize

Using versions:
"serverless-appsync-plugin": "^1.10.0"
serverless@2.36.0

**Comment by bserefaniuk** [comment]
I've got the same issue today...

**Comment by joaocostamm** [comment]
I changed serverless to: serverless@2.35.0
This version works...

**Comment by bserefaniuk** [comment]
We already can use serverless@2.37.0 where it's fixed (https://github.com/serverless/serverless/issues/9333)

**Comment by pgrzesik** [comment]
This was an unintended bug introduced in `2.36.0` version of the Serverless Framework. In order to fix it, upgrade to the latest version and I believe this issue could be closed as it's definitely not an issue with the plugin itself.

**Comment by bboure** [comment]
Thank you @pgrzesik and @bserefaniuk 

Will close this now
