### ISSUE TITLE
Configuring managed rules for WAF

### ISSUE THREAD

**Issue by sc0ttdav3y** [sid88in/serverless-appsync-plugin#412]
Hi,

I've been configuring AWS Managed Rule Groups into my WAF and have had some troubles with lacking documentation as well as a problem with the plugin's CloudFormation output, that means I can't add these groups currently.

By reading docs, reading through the plugin's code and through trial and error I've worked out that the following configuration is what we want:

```
    wafConfig:
      rules:
        - name: MyRule1
          overrideAction:
            none: {}
          statement:
            managedRuleGroupStatement:
              vendorName: AWS
              name: AWSManagedRulesCommonRuleSet
```

According to AWS docs, when working with Managed Rule Groups in CloudFormation we need to specify `OverrideAction` but not include `Action`. 

References: 

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-ruleaction.html
- https://docs.aws.amazon.com/waf/latest/developerguide/waf-using-managed-rule-groups.html

First, if you don't specify `overrideAction` in our yaml, you get this error:

```
  An error occurred: GraphQlWaf - Resource handler returned message: "Error reason: A reference in your rule statement is not valid., field: RULE, parameter: Statement (Service: Wafv2, Status Code: 400, Request ID: XXXX, Extended Request ID: null)" (RequestToken: XXXX, HandlerErrorCode: InvalidRequest).
```

To solve this error, I found I needed to supply `OverrideAction` in CF (which is `overrideAction` in yaml). But this is where a plugin bug kicks:

```
  An error occurred: GraphQlWaf - Resource handler returned message: "Error reason: You have used none or multiple values for a field that requires exactly one value., field: RULE, parameter: Rule (Service: Wafv2, Status Code: 400, Request ID: f6c42a34-3737-4c2c-8721-a8f1d01e4418, Extended Request ID: null)" (RequestToken: be2518c6-49e7-6a47-00b2-53aac33b3eae, HandlerErrorCode: InvalidRequest).
``` 

By diving into the code I found success with a modification that conditionally suppresses `Action` whenever `OverrideAction` is defined. It appears they are mutually exclusive in CF, so they should be mutually exclusive in this plugin too.

With this change, the above yaml correctly configures the managed rule group 🎉 

I've got [this PR](https://github.com/sid88in/serverless-appsync-plugin/pull/413) ready with the change as well as some documentation changes to help others.

**Comment by bboure** [comment]
Fixed in #413
