### ISSUE TITLE
Serverless plugin "serverless-appsync-plugin" initialization errored: Unexpected token .

### ISSUE THREAD

**Issue by lolcoolkat** [sid88in/serverless-appsync-plugin#43]
When I try to deploy I get this.. running from the example.. :(

![Error](https://image.prntscr.com/image/ioBXTWXuRayRJgjCdCBbOA.png)

**Comment by sid88in** [comment]
@lolcoolkat were you able to resolve this? I have to publish new npm package

**Comment by lolcoolkat** [comment]
Yes I have resolved this! Working on adding some update functionality to the plugin aswell :)

**Comment by lolcoolkat** [comment]
@sid88in will do when im done :)

**Comment by honkskillet** [comment]
@lolcoolkat I get a similar error

serverless plugin "serverless-appsync-plugin" initialization errored: Unexpected token )

How did you resolved your error?

**Comment by sid88in** [comment]
@honkskillet I think you need to use latest node / serverless package version

**Comment by honkskillet** [comment]
Ah. Yes.  Old node.  Thank you.

**Comment by fgiarritiello** [comment]
Hi,

I'm getting the following error as well when I try to run `serverless deploy`

`serverless plugin "serverless-appsync-plugin" initialization errored: Unexpected token )`

this is my environment
``` 
OS: darwin
Node Version: 6.12.1
Serverless Version: 1.27.3
```

any help will be appreciated.

tnx
