### ISSUE TITLE
Question about Repo usage.

### ISSUE THREAD

**Issue by borreda** [sid88in/serverless-appsync-plugin#452]
I have been researching for a solution to deploy an appsync server fast and easy and came across 2 of your  repositories.
May you help me understand which one should I use?(looks like this is the newest)

https://github.com/sid88in/serverless-appsync-plugin

And

https://github.com/serverless/serverless-graphql

In addition, I saw that the newest post about it was in 2018, and under limitation, you wrote "missing support for dynamodb batch operation" 
I was wondering if your repositories include that support since appsync already supports it.(?)

Your article:
https://www.serverless.com/blog/running-scalable-reliable-graphql-endpoint-with-serverless/
Aws doc:
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html

Thank you in advance for the help.

**Comment by bboure** [comment]
This repository is the one to use if you want to use the Serverless Framework. 

https://github.com/serverless/serverless-graphql is just an example of use

Not sure where you saw "missing support for dynamodb batch operation" but these are fully supported in AppSync.

**Comment by borreda** [comment]
thank you for the help
