### ISSUE TITLE
Discussion/Proposal for update/delete functionality with serverless-appsync-plugin

### ISSUE THREAD

**Issue by lolcoolkat** [sid88in/serverless-appsync-plugin#49]
Wanted to create a little discussion here for anyone interested.. to talk about a proposal for how the update/delete functionality might work in the future. 

Atm there is a `cleanupDataSources` function that makes an api call to AWS to find out what data sources you have on your API and compares it to the data sources you have set in your serverless.yml file. With that information it can determine what data sources aren't being used anymore and delete them. (But this could get a little bit tricky when a config grows to a large number of data sources/resolvers)

My proposal would be to; instead of making http requests to find out the data sources/resolvers needed to delete.. create a snapshot of the serverless.yml file.. and save it in a folder or something named snapshots or w/e.

With that snapshot; all you would need to do is compare locally.. that file and also your new config file that you are changing. It would determine the changes.. and make the necessary deletes to your API.

Hope we can get a few other people to weigh in on this.. and maybe share their ideas :)

**Note**: Snapshot files would also be good for doing rollbacks to a certain date.. or the last saved config.. or something like that as well. Maybe snapshots can have dates appended to the file names .. so u can rollback to a certain date, etc.

If anyone wants to check out the rough example I came up with on my fork you are more then welcome :) https://github.com/lolcoolkat/serverless-appsync-plugin/blob/master/index.js

I replaced the updateDataSources with a more general function (maybe should be split into multiple functions later) that cleans up the data sources/resolvers you aren't using, and also creates a snapshot at the end.. for future updates!

**Comment by sid88in** [comment]
thanks @lolcoolkat for looking into this. Let's discuss it sometime next week, I'll think more on this.

**Comment by DaleJefferson** [comment]
I would expect that the representation in the serverless.yml would be replicated on the server, it sounds like what you are suggesting does not fit that mental model.

If I create datasources in the UI but don't add them to the serverless.yml it sounds like they will not be removed on next deploy?

**Comment by lolcoolkat** [comment]
@DaleJefferson I think the whole idea behind this project is to create an offline solution for adding/removes data sources/resolvers. If you are to add data sources to your UI.. and using this package.. you should add it to your serverless.yml file aswell :)

But building off your idea..maybe something that can check for any manually added functions and syncs your config with it :)

**Comment by maziarz** [comment]
Awesome plugin. Only issue i have right now is that i need to create a workaround to maintain multi stage setup (dev, beta, prod). `apiId` is necessary for provisioning, but how do we get about providing an input with multiple `apiId` depending on stage? Is an environment file the best option?

**Comment by ldgarcia** [comment]
When you try either of the following:
1) Rename a datasource, in both `dataSources` and `mappingTemplates`. Run `update-appsync`.
2) Assign the resolvers to a newly defined datasource and remove the old datasource definition from your config. Run `update-appsync`.

The plugin tries to delete the remote/deployed datasource and fails (_Error: Resolver associated with data sources_) if it is associated to one or more remote resolvers (with the old name).

So, currently, one must use a two-pass migration:
1) Define the new datasource and update the resolver definitions to use that datasource. Run `update-appsync`.
2) Remove the old datasource definitions. Run `update-appsync`.

Would it be useful if the plugin does this automatically? Or is it better to explicitly create the new (renamed) datasources first and then delete the old datasources?
