### ISSUE TITLE
Quiet mode for custom domains

### ISSUE THREAD

**Issue by ChristopherGillis** [sid88in/serverless-appsync-plugin#524]
I'd like to have the create domain step be part of our deploy pipeline, which means I'd like to have it not throw an error if the domain already exists.

I see in the code a quiet option, but I can't get it to work.

https://github.com/sid88in/serverless-appsync-plugin/blob/a2bb44a211ab23d725a8b21dae58564393d3ab9d/src/index.js#L106

Any ideas?

**Comment by bboure** [comment]
You should be able to do
```
sls appsync-domain create -q
```

let me know if that does not work

**Comment by ChristopherGillis** [comment]
It does not work

**Comment by bboure** [comment]
I'll have a look when I have a moment.

**Comment by ChristopherGillis** [comment]
This is working now. Note that assoc does not require -q. It fails cleanly by default.
```
          "sls appsync-domain create -q",
          "sls appsync-domain assoc",
          "sls appsync-domain create-record -q"
```
