### ISSUE TITLE
Custom Domain Auto-DNS with Route53.

### ISSUE THREAD

**Issue by ChristopherGillis** [sid88in/serverless-appsync-plugin#525]
The Custom Domain functionality sets up a custom domain in AppSync, but does not update the Route53 to point a record to it... Could this be added as a feature?

There is a plugin here, which does something similar, but for API Gateway. https://www.serverless.com/plugins/serverless-domain-manager

**Comment by bboure** [comment]
There is a command for that
[Check the doc](https://github.com/sid88in/serverless-appsync-plugin#createdelete-a-route53-record)

**Comment by ChristopherGillis** [comment]
Thanks, I must have missed that.
