### ISSUE TITLE
How to handle API Key expiry in production?

### ISSUE THREAD

**Issue by sc0ttdav3y** [sid88in/serverless-appsync-plugin#535]
Hi all,

Not a bug — I'm looking for some advice.

Say I enable api key expiry. Then what? Does anyone have any in-the-trenches advice on how to renew and cycle API keys created through this plugin?

Here my scenario:

1. I have a client internally within my AWS environment that needs to interact with AppSync, and I'm using an API key for this client.
2. This client is part of a Lambda function within my serverless stack, so I can supply the key built with this plugin via a SSM Parameter or a Secrets Manager secret.
3. However, when the API key expires, my reading of the README suggests the client will stop working and the next deployment will simply fail. The workaround seems to be to remove the key and add a new one in yml and then redeploy. 

This expiry and renewal approach feels problematic, and I'm wondering whether anyone in the community has a workflow or advice to address this, other than dropping a reminder onto my calendar to remind me each anniversary?

Thanks!

**Comment by bboure** [comment]
Hi,

Sorry, the doc might not be clear about this. here is how it works:

By default, keys expire after one year and are renewed (extended) after each deployment (expires 1 year after the deployment)
As long as you deploy at least once a year, your API key will always be active. 

If you use a custom expiry with `expiresAfter` (e.g 30 days), then you'll have to deploy once a month to extend the key. 

The 60 days the doc refers to is the time AWS AppSync gives you to renew/extend an expired key. After that, it will become unrenewable. This is when you might start having issues with deployments. To renew a key that expired < 60 days ago, just redeploy.

Note: if you use `expiresAt` then the key will always expire at that exact moment, it will never be renewed by the plugin (unless you change the expiry date)

Keys can never expire > 1 year from "now"

**Comment by sc0ttdav3y** [comment]
@bboure, you're a legend and a scholar. That is much better news than I was expecting 🥇🥇🥇. 

Here's some proposed README wording I've whipped up that may clear it up for others. What do you think?

--- 

**API Key Rotation**

This plugin handles key rotation for you as follows:

* If you set `expiresAfter`, simply deploy at least once within the validity period to renew it automatically.  For example, for `expiresAfter: 30d`, maintain a < 30 day release cycle. At each release the expiry is extended by 30 days. If you forget to deploy and the key does happen to expire, simply deploy again within 60 days of expiration to automatically renew it.
* If using `expiresAt`, you need to manually edit your yml file to update the expiry value, and then deploy prior to the key expiring. If it happens to expire, you can renew it by following the deploy step within 60 days after expiration.

**Using the key in other parts of your project**

To access the key within CloudFormation or other parts of your serverless stack, use the following reference: `!Ref GraphQlApiKeyXXX`, where `XXX` is the `name` property you've given the key.

---

**Comment by bboure** [comment]
Looks good to me!
Feel free to open a PR,

if you do, please open two: one for `master` and one for `alpha` for v2.
The behaviour has not changed

**Comment by sc0ttdav3y** [comment]
Will do, thanks.
