### ISSUE TITLE
Access nested arguments?

### ISSUE THREAD

**Issue by gel-hidden** [sid88in/serverless-appsync-plugin#548]
Lets say I have a query like this:

```
extend type Query {
    streets(number: Int): [Street]
}

type People {
   name: String
}

type Street {
    number: Int
    name: String
    people(name: String): [People]
}
```

And would then send a query like:

```
query  { streets(number: 1) { name, people(name: "Hello world") { name } } }
```

I don't see to be able to fetch the `name` argument of people. The `$ctx.arguments` just gives me:

```
 arguments: { number: 1 }
```

Is there no way to access both the `number` argument as well as the `name` argument?

**Comment by bboure** [comment]
Hi,

This is by (AppSync) design (not this plugin specifically) 
The resolver attached to the `Query.street` will receive the `number` argument. 
The `name` argument,

**Comment by gel-hidden** [comment]
Oh, sorry. I'm lacking quite a bit of knowledge in this area.

I have the same resolver, I think, for both `Street` and `People` given it is only one query. But I should configure it so it should be two revolvers for the same query? So one single query is calling multiple lambda resolvers?

**Comment by bboure** [comment]
I'd say you have two options:

- move the `personeName` at the root of your query (in `street`) and keep one resolver to resolve everything.
- Use another resolver and that resolves the person separately

**Comment by gel-hidden** [comment]
And by using another resolver it also means I have another query? Or could one query use multiple resolvers?

**Comment by bboure** [comment]
you can attach a resolver on `Street.People` it will be executed and you will receive the result `ctx.source`  from the previous resolver.

I suggest you read the [doc and guides](https://docs.aws.amazon.com/appsync/latest/devguide/what-is-appsync.html) and learn more about GraphQL in general first.

**Comment by gel-hidden** [comment]
Thank you so much!
