### ISSUE TITLE
Multi stage AppSync API's

### ISSUE THREAD

**Issue by maziarz** [sid88in/serverless-appsync-plugin#55]
Is there a workaround to maintain multi stage setup (dev, beta, prod). `apiId` is necessary for provisioning, but how do we get about providing an input with multiple `apiId` depending on stage? Is an environment file the best option?

**Comment by sid88in** [comment]
@maziarz I am not exactly sure if I understand your use case. Looks like you want to generate multiple api keys for dev/stage/prod? One way might be to provide the value of api id in package.json (based on the enviornment) and access the value in serverless.yml using ${opt:apiId}. You may also use env cmd utils.

**Comment by maziarz** [comment]
@sid88in thanks for the reply. I may have excluded some details, sorry for that. Essentially what i need is a serverless setup that is replicated across different stages, so i would basically just be able to deploy the exact same setup into different stages. I have already found a solution for the other services (lambda, dynamodb, s3, etc.), but since AppSync is not "driven" by the API name but the `apiId` i cannot simply concat `-dev`, `-beta` or `-prod`, to its name, so i need to have an additional environment variable that takes care of that contextual switching between the AppSync API depending on which stage i am working in.  As i understand you suggest that i use `package.json` to add the extra dimension of variables or env cmd utils.

**Comment by sid88in** [comment]
yes you should be able to pass this apiId in serverless.yml via package.json. To me this problem seems more specific to creating serverless resources based on different env. You can also ask these questions here: serverless-contrib.slack.com

**Comment by harleyguru** [comment]
This issue should be opened again.

Actually, we all expect change of AppSync name should create new AppSync API. But it changed API name itself.

What's the best way to have multiple AppSync APIs?
Because AppSync API is created by your plugin, this should be discussed here.

**Comment by harleyguru** [comment]
so with current version, can't we deploy multiple AppSync APIs?
I could deploy another one by changing just stage.
