### ISSUE TITLE
Specify WAF arn in V2.

### ISSUE THREAD

**Issue by ivan-branets** [sid88in/serverless-appsync-plugin#575]
In v1 of this plugin, it was possible to specify the ARN of WAF ACL. This allowed using existing ACLs and rules instead of creating a new ones. Is it going to be supported in v2?

https://github.com/sid88in/serverless-appsync-plugin/blob/fff6f31572921b9603c8bcc38088afdc4c0aab5f/src/types/plugin.ts#L27

Thanks

**Comment by bboure** [comment]
Hi,

I just merged PR #504 which adds support for that. 
It is available in v 2.1.0

https://github.com/sid88in/serverless-appsync-plugin/blob/master/doc/WAF.md#quick-start
