### ISSUE TITLE
Javascript resolvers supported now by AWS as Unit resolvers but not by the plugin

### ISSUE THREAD

**Issue by andrea-oo** [sid88in/serverless-appsync-plugin#616]
Hey guys,

AWS now supports JS resolvers as UNIT resolvers however if i define them as `kind: UNIT` into the serverless config of your plugin  it throws an error on deploy asking for the Mapping templates(related to VTL resolvers).

If i define them using the `functions:` sintax for pipeline resolvers then it works fine but as pipeline resolvers.

When are you gonna add the support for JS unit resolvers? if it is still supported what's the sintax to write them ? 

Many thanks!

**Comment by bboure** [comment]
Hi @andrea-oo 

There is a PR open for that #613 
Please have a look

I'll try to release that asap

**Comment by andrea-oo** [comment]
that's great thank you !

**Comment by zachrmh** [comment]
Yes thank you! Much needed for our project, I'll be keeping an eye out for this in the next release 🙌 🙌 🙌

**Comment by zachrmh** [comment]
Awesome thank you 👏 👏
