### ISSUE TITLE
Extend this plugin - GraphQL codegen

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#62]

**Comment by ldgarcia** [comment]
Hi @sid88in, I am currently using [gql-merge](https://github.com/liamcurry/gql) to create the appsync schema file from multiple smaller files. Are you referring to something like this?

**Comment by sid88in** [comment]
@ldgarcia maybe. I am open to suggestions. Basically thinking that this plugin should be able to autogenerate mapping-templates or graphql resources based on graphql schema - for ex https://github.com/apollographql/apollo-codegen

**Comment by merunga** [comment]
@sid88in I've created some npm scripts to do exactly this. Checkout this [gist](https://gist.github.com/merunga/2b6d2292c5e04417c1649106071bbdcd).
If that's close to what you had in mind, let's talk it out, and I can try to integrate it in the plugin. I uses [merge-graphql-schemas](https://github.com/okgrow/merge-graphql-schemas) and [apollo-codegen](https://github.com/apollographql/apollo-codegen)

**Comment by sid88in** [comment]
@merunga amazing! Let's get on a skype call this/next week and talk it out? Can you please reach out to me on Twitter DM (sidg_sid) and we can plan something. 

thanks

**Comment by sid88in** [comment]
@merunga any updates on this? Looking forward.

**Comment by CiscoKidxx** [comment]
@sid88in - did we get ghosted?

**Comment by sid88in** [comment]
I think we can close this PR and focus on integrating AppSync Amplify Utils with this plugin for codegen

**Comment by trilliput** [comment]
I'm considering to extend the plugin a bit to support several schema files based on [merge-graphql-schemas](https://github.com/okgrow/merge-graphql-schemas). The idea is to support following options:
**1. Current implementation stays as is**
```
custom:
  appSync:
    schema: path/to/schema.graphql
```
**2. The array of paths is going to be merged by  [merge-graphql-schemas](https://github.com/okgrow/merge-graphql-schemas)**
```
custom:
  appSync:
    schema:
      - path/to/schema_base.graphql
      - path/to/schema_internal.graphql
```
@sid88in is there a chance a PR with this kind of implementation would be merged even though you're working on integration of AppSync Amplify Utils? My points are: a simple solution might be still useful and I don't have time to wait to the Amplify integration.

**Comment by SET001** [comment]
can we use [graphql-tag](https://github.com/apollographql/graphql-tag) with this plugin?
