### ISSUE TITLE
Extend this plugin - Travis Build

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#64]

**Comment by nadalfederer** [comment]
`npm test` not working

1. 
![image](https://user-images.githubusercontent.com/6043510/37873756-80af1246-302b-11e8-8630-615111273e6a.png)

the problem with path. If delete second parametr it will launch.
`const servicePath = path.join(__dirname, '..', 'example');`

2. 
snapshot test failed.
![image](https://user-images.githubusercontent.com/6043510/37873748-431d4498-302b-11e8-8bc9-8c7a0e05a531.png)

**Comment by sid88in** [comment]
@nadalfederer thanks for looking into it. I didn't get time to look any further into this, but maybe you can create a PR and I can further investigate this?

**Comment by sid88in** [comment]
thanks @bboure for taking care of this!
