### ISSUE TITLE
Looking for contributors! 

### ISSUE THREAD

**Issue by sid88in** [sid88in/serverless-appsync-plugin#69]
- working with GraphQL?
- have good ideas on how to extend this plugin?
- love working with opensource? 

Please reach out to me :) 
Thanks
Sid

**Comment by honkskillet** [comment]
What do you need the most help with?

**Comment by sid88in** [comment]
@honkskillet I opened some issues, feel free to take a look. I think auto-generating GraphQL schema would be super helpful and based on that we should be able to auto-generate mapping templates.
