### ISSUE TITLE
More Verbose Errors

### ISSUE THREAD

**Issue by honkskillet** [sid88in/serverless-appsync-plugin#73]
When I try to deploy I get the following error...

  Serverless Error ---------------------------------------
  Request mapping template not specified.
 
Since I am adapting this from the example I had tried to go through and comment out all the graphql queries/mutations/subscriptions that don't have a mapping template specified but I still get this error.  It would be very helpful if the error would reference what in the graphql schema was lacking a mapping template.

Also, might it be better if unspecified mapping templates give a warning and not an error?

**Comment by honkskillet** [comment]
PS  I figured out the error that was causing this in my particular project.

**Comment by sid88in** [comment]
what's causing the error?
