### ISSUE TITLE
lambda function not created

### ISSUE THREAD

**Issue by honkskillet** [sid88in/serverless-appsync-plugin#74]
I am trying to create a AppSync stack that uses just lambda functions instead of DynamoDB. 
Running deploy-appsync creates the project.  Every thing in this AppSync console looks good.  But when I click on link to the lamba function in **AWS AppSync > myApi > Data Sources** it flashes an error (flashes it so quickly I cannot read it) before redirecting me to my list of lambda functions where it appears that the lambda function has not been created.  When I check in the AWS CloudFormation console it also appear there is no evidence of any resources there either. 

<img width="1468" alt="grab" src="https://user-images.githubusercontent.com/2345665/38468600-b571ce9c-3b16-11e8-978f-bce68d7e81c6.png">
(image shows a link to the lambda function but there is no function there when I hit the link.  Seems it wasn't created.)

Here is my serverless.yml.  It is a modified version of the example.  I am thinking there is something missing from the resources section?
```service: ServerlessAppSync
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2  
functions:
  hello:
    handler: handler.hello
plugins:
   - serverless-appsync-plugin
custom:
  accountId: [redacted] # found here https://console.aws.amazon.com/billing/home?#/account
  appSync:
    name:  serverlessAPI # defaults to api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: us-west-2  # required # region
      defaultAction: ALLOW
      userPoolId: us-west-2_SHawmnz0D # required # user pool ID
      region: us-west-2 # defaults to provider region
    mappingTemplatesLocation: mapping-templates # defaults to mapping-templates
    mappingTemplates:
      - dataSource: Serverless_Lambda_DS # data source name
        type: Query # Query, Mutation, Subscription
        field: getUserInfo
        request: getUserInfo-request-mapping-template.txt # request mapping template name
        response: getUserInfo-response-mapping-template.txt # response mapping template name
    schema: schema.graphql # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AWS_LAMBDA
        name: Serverless_Lambda_DS  # data source name
        description: 'Lambda DataSource'
        config:
          lambdaFunctionArn: "arn:aws:lambda:us-west-2:${self:custom.accountId}:function:serverless-lambda-dev-graphql"
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Lambda-${self:custom.appSync.serviceRole}"
resources:
  Resources:
    AppSyncLambdaServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Lambda-${self:custom.appSync.serviceRole}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Lambda-${self:custom.appSync.serviceRole}-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                  Resource:
                    - "arn:aws:lambda:us-west-2:${self:custom.accountId}:function:serverless-lambda-dev-graphql"
                    - "arn:aws:lambda:us-west-2:${self:custom.accountId}:function:serverless-lambda-dev-graphql:*"```

**Comment by honkskillet** [comment]
1. I will check against that yml that you provided.  The yml that I am using is basically just from the example of this project, with stuff deleted to make it as minimal as possible (ie old one query so only 1 pair of template, and I deleted the dynamoDB and ES resources).

2.  Basic serverless works.  I just did a create and deploy to confirm.

**Comment by sid88in** [comment]
1) yeah doublecheck, please. I am pretty sure, the code in serverless-graphql for this example works (and has been tested). but the example in this repo might not have been updated for some reason. Try deploying the appsync example in that repo (with the code given above) to see if that helps and then you can reverse engineer your code. Also, if you identify any missing pieces in the example in this repo, feel free to create a PR.

2) sounds good

thanks

**Comment by honkskillet** [comment]
OK.  I will try the example you gave, then try stripping things out until I just have the basic Lambda function I am looking for.  If I get it working I'll do a pull request to add it to examples.

**Comment by honkskillet** [comment]
Is https://github.com/serverless/serverless-graphql/blob/master/app-backend/appsync/lambda/serverless.yml also tested and working?

**Comment by sid88in** [comment]
yes

**Comment by honkskillet** [comment]
Hmm.  I have the same problem with both those lambda and dynamo-elasticserach-lambdo examples.  The AppSync backend is generated (graphQL, templates, links to data sources), however the actual lambda function is not created.

**link to the lambda function visible in the AppSync console...**
<img width="1204" alt="appsyncgrab" src="https://user-images.githubusercontent.com/2345665/38472664-5f8f5e00-3b51-11e8-8720-b11918d681e5.png">

**...but that function is not present in the Lambda console**
<img width="867" alt="lambdagrab" src="https://user-images.githubusercontent.com/2345665/38472745-962d3738-3b52-11e8-9a05-c7342d861714.png">

The deploy looked good
```$ serverless deploy-appsync
Serverless: Creating GraphQL Endpoint...
Serverless: GraphQL API ID: h5fqwde5uzhhfe2v6v55vl2vuy
Serverless: GraphQL Endpoint: https://pj6cdzgn2vbh7n7qf4erecfmxy.appsync-api.us-west-2.amazonaws.com/graphql
Serverless: Attaching data sources...
Serverless: Created new data source: myDynamoDB
Serverless: Created new data source: myLambda
Serverless: Created new data source: myElasticSearch
Serverless: Creating GraphQL Schema
Serverless: PROCESSING | The schema is being processed.
Serverless: PROCESSING | The schema is being processed.
Serverless: PROCESSING | The schema is being processed.
Serverless: PROCESSING | The schema is being processed.
Serverless: PROCESSING | The schema is being processed.
Serverless: SUCCESS | Successfully created schema with 7 types.
Serverless: Schema for GraphQL endpoint created...
Serverless: Getting schema for GraphQL endpoint...
Serverless: Creating resolvers...
Serverless: Created new resolver on field: getUserInfo
Serverless: Created new resolver on field: topTweet
Serverless: Created new resolver on field: tweets
Serverless: Created new resolver on field: createTweet
Serverless: Created new resolver on field: meInfo
Serverless: Created new resolver on field: deleteTweet
Serverless: Created new resolver on field: reTweet
Serverless: Created new resolver on field: updateTweet
Serverless: Created new resolver on field: updateUserInfo
Serverless: Created new resolver on field: searchTweetsByKeyword
Serverless: Created new resolver on field: searchAllTweetsByKeyword
Serverless: Created new resolver on field: favourites_count
Serverless: Type List: Mutation,Query,Subscription,Tweet,TweetConnection,User,schema
Serverless: All done deploying/updating data sources and resolvers.```

**Comment by honkskillet** [comment]
AH!  I thought the pluggin was also running the basic `serverless deploy`.  I misread what you meant in your very first response.  Thank you for the help.

**Comment by honkskillet** [comment]
I got the project working.  It's a minimal example with just a lambda data source (no dynamoDB or ES).  Would you want this as an example?

**Comment by tynandebold** [comment]
@honkskillet I'd like to see that example if you still have it. I'm working on something similar right now and what you created sounds very similar to what I'm trying to do.
