### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by patrick91** [sid88in/serverless-appsync-plugin#75]
It would be amazing to have offline support for this :)

**Comment by sid88in** [comment]
totally :) There is offline support for dynamoDB. Not sure if its inherently provided by AWS or was created. Thinking if its even possible to have offline support for AppSync without any AWS packages.

**Comment by patrick91** [comment]
I don't think you need a aws package for this, might be easy enough to read the schema and use the yaml configuration to map the resolvers

**Comment by sid88in** [comment]
hmm yeah mapping resolvers to actionable code will be the key. Wana take a stab at it?

**Comment by guilhermedecampo** [comment]
Hey guys how this is going? I have no clue how to make it happen 🤔

**Comment by aheissenberger** [comment]
I created a plugin which provides offline support based on the excelent Appsync Emulator from @lightsofapollo and his team:
https://github.com/aheissenberger/serverless-appsync-offline

This should resolve #114

**Comment by sid88in** [comment]
@aheissenberger thats great. can you please update read me in this repository to point to your offline repository and some basic steps. 

thanks

**Comment by lucasvieirasilva** [comment]
hi @aheissenberger your plugin has a problem when I try install on Windows.

Like this:

```
> graphql-phone-type@0.0.2 lint C:\Users\username\AppData\Local\Yarn\Cache\v4\.tmp\ba08b149d9e36e6bca89db26836f5f97.daaa07a9705b8a4669acd5f98a599ab443cb31d6.prepare
> eslint src demo


C:\Users\username\AppData\Local\Yarn\Cache\v4\.tmp\ba08b149d9e36e6bca89db26836f5f97.daaa07a9705b8a4669acd5f98a599ab443cb31d6.prepare\src\index.js
   1:65  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:66  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
```

Can you fix this?

Thanks

**Comment by cbaron** [comment]
@lucasvieirasilva -- I believe this is related to an [issue](https://github.com/ConduitVC/aws-utils/issues/73) in our appsync-emulator-serverless repo.
