### ISSUE TITLE
Separate process.env yaml?

### ISSUE THREAD

**Issue by honkskillet** [sid88in/serverless-appsync-plugin#78]
It seems like some things (like accountId) should be separated into it's a yml (or json) file that gets mapped to porcess.env.  Many serious projects will need to take advantage of  process.env at some point.  Is there a best way to do this for aws lambdas?

**Comment by honkskillet** [comment]
I'm going to quick close this because I think it really belongs to serverless and not serverless-appsync-plugin.

**Comment by honkskillet** [comment]
Ah.  Thank you.

**Comment by honkskillet** [comment]
I notice non (most?) of the examples don't use it.   Are they just lagging behind?  So you would put a config folder at the same level as the serverless.yml?

**Comment by sid88in** [comment]
depends on the use case.
