### ISSUE TITLE
update-appsync with Lambda Resolver

### ISSUE THREAD

**Issue by michaelrhoden** [sid88in/serverless-appsync-plugin#81]
First, thank you for developing this great plugin. I have been setting up Appsync over the last week and it is awesome to use, given there is a good bit of trial/error, due to limited Appsync documentation. 

I have run into a bug, possibly due to recent changes to Appsync. When you run the sls update-appsync and you have a "Lambda Data Source" (for a Lambda based resolver), it drops the role after each update. Deploy seem to work. So every time I run update-appsync, I have to go click the dropdown in datasource and set the Region, Function Arn, and role to make every work. The update throws no errors, and was a pain to chase down when my query just stopped working. 

Right after an update (before I set the ARNs/Role) the Lambda Resolver returns: java.lang.IllegalArgumentException: Illegal ARN format detected, the relative-id must follow the format function:<name>:<alias>

-Michael

**Comment by michaelrhoden** [comment]
If I had to guess the issue, it appears:

awsRegion: resolvedConfig.region,

is being set for the other datasources. Maybe add at Line 185 of index.js?

-Michael

**Comment by michaelrhoden** [comment]
Just confirmed by adding that line (awsRegion: resolvedConfig.region,) on my local, that it fixes the issue. What is the process of submitting that change to the repo. Haven't ever submitted code to github for a pull request.

**Comment by sid88in** [comment]
@michaelrhoden would be great if you can submit a PR? Just fork this repo and then create a PR. Please add screenshots to make sure its working thanks!

**Comment by honkskillet** [comment]
PR = pull request

**Comment by sid88in** [comment]
@peterfennema I'll try update-appsync with lambda resolver next week and will keep you posted. @michaelrhoden if you already have fixed this, feel free to create a PR.

thanks

**Comment by hounded** [comment]
I'm still having this issue, when deploying I get no issues but my lambda datasources are not setting the region @peterfennema did you manage to fix this?

**Comment by peterfennema** [comment]
@hounded No, I'm not using this plugin anymore (for other reasons, not because of issues with this plugin)
