### ISSUE TITLE
Make `apiKey` optional for update-appsync

### ISSUE THREAD

**Issue by kulesa** [sid88in/serverless-appsync-plugin#83]
Could you make `apiKey` config param optional? I found that most of the time I run update-appsync to change only schema and/or mapping templates, and having to provide a valid API key for each update complicates the task, especially when you have few APIs and keys are rotated often.

**Comment by sid88in** [comment]
@kulesa do you mean apiKey optional for update app sync?

**Comment by kulesa** [comment]
@sid88in yes. Basically, this line https://github.com/sid88in/serverless-appsync-plugin/blob/master/index.js#L167 should also check that resolvedConfig.apiKey is present. I can open a pull request if you're okay with this change

**Comment by sid88in** [comment]
that'd be great! please test it once and add screenshots as well ;)
