### ISSUE TITLE
Re-make this as a Serverless Component

### ISSUE THREAD

**Issue by lolcoolkat** [sid88in/serverless-appsync-plugin#86]
I think this repo should be re-made using https://github.com/serverless/components

It can then be deployed to the Serverless Components registry that other users can use. There are already a bunch here https://github.com/serverless/components/tree/master/registry

:)

**Comment by sid88in** [comment]
@lolcoolkat thanks for pointing this out. We should totally explore this option. I need to spend some time to understand components (I think its a new feature). If you have some time, maybe we can connect and discuss best way to proceed here.

**Comment by bboure** [comment]
https://github.com/serverless-components/aws-app-sync
