### ISSUE TITLE
Configure Logging for Appsync Api

### ISSUE THREAD

**Issue by nitshooda** [sid88in/serverless-appsync-plugin#89]
For individual data source we can configure cloudwatch, but how to configure it for whole Appsync Api like we have option in console.

**Comment by cameronrll** [comment]
Would like to know this aswell

**Comment by btorresgil** [comment]
@sid88in  Created Pull Request #96 to resolve this issue.  Tested working for my own serverless app.  Thanks for creating this great plugin!
