### ISSUE TITLE
Refactor to deploy resources in the serverless cloudformation stack

### ISSUE THREAD

**Issue by ajmath** [sid88in/serverless-appsync-plugin#90]
The current setup with having additional commands to execute outside of a typical `sls deploy` that create resources that aren't tied to the sls CloudFormation stack is problematic for a number of reasons:
* Non-abstracted dependency and versioning/rollback issues of having to execute `sls deploy` and `sls appsync-deploy` or `sls appsync-update` sequentially
* Requirement of updating configuration after performing a deploy to inject the `apiId`
* Having to know whether to call update or deploy
* Isolated resources cannot be easily cleaned up with the rest of serverless stack
* Obfuscation of what resources this plugin is actually creating
* Inability to further customize the generated resources as new features are added to AppSync

I believe this change would also address these issues:
* #76 
* #81
* #49 

I plan on implementing this myself for a project I'm working on now and I'd like to contribute back. @sid88in Would you be open to accepting a PR that implements this?

We could implement this in one of two ways, breaking or non-breaking.  I think the breaking change would be recommended as we want to enforce this behavior by default going forward and reduce accumulation of technical debt.

For the breaking change, I would propose this acceptance criteria:
* Compatibility with existing configuration block with the exception of apiId
* Hooks into `before:deploy:deploy` lifecycle event to add AppSync resources to  `serverless.service.provider.compiledCloudFormationTemplate.Resources`
* Log and return an error when `appsync-update` or `appsync-deploy` is called

**Comment by honkskillet** [comment]
I agree with this plan. Everything should be built with sls deploy and all resources should end up in the cloud formation stack.
