### ISSUE TITLE
Webpack Support

### ISSUE THREAD

**Issue by austin43** [sid88in/serverless-appsync-plugin#92]
It would be great to have Webpack support so we can utilize a loader for our schema.graphql rather than packing our entire schema into a single file.
https://github.com/samsarahq/graphql-loader

**Comment by rohanray** [comment]
Hi @austin43 

I have split my types, inputs, queries & mutations in separate individual files. All files are present under <root_project_directory>/schemas.

I have an npm script `merge-schemas` as below:

```
"scripts":{
  "merge-schemas": "cat schemas/*/*.graphql > ./schema.graphql",
  "update": "npm run merge-schemas && sls update-appsync -v"
}
```

I just invoke that script inside update script, so it merges all schemas to one single file: `<root_project_directory>/schemas/schema.graphql` prior to running `sls update-appsync`

Hope that helps

**Comment by ldgarcia** [comment]
You can also use [`gql-merge`](https://github.com/liamcurry/gql/tree/master/packages/gql-merge): 

````bash
gql-merge --out-file appsync/schema.graphql appsync/schema/*.graphql
````
This way you can define the queries and mutations for a type in their own file, for example:

`posts.graphql`:
````graphql
type Post {
  id: ID!
  content: String
}

type Query {
  postById(id: ID!): Post
}
````

`authors.graphql`:

````graphql
type Author {
  id: ID!
  name: String
}

type Query {
  postsByAuthorId(id: ID!): [Post]
}
````

If you want to validate the merged schema, you can also use [`graphql-schema-linter`](https://github.com/cjoudrey/graphql-schema-linter):

````bash
gql-merge --out-file appsync/schema.graphql appsync/schema/*.graphql && graphql-schema-linter -r \"defined-types-are-used enum-values-all-caps fields-are-camel-cased input-object-values-are-camel-cased relay-connection-types-spec relay-connection-arguments-spec types-are-capitalized\" appsync/schema.graphql
````

**Comment by bboure** [comment]
We now support schema stitching.
